# Generated by Django 5.2.13 on 2026-05-04 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(db_index=True, max_length=64)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=16)),
                ('theme', models.CharField(max_length=200)),
                ('planned_activities', models.TextField()),
                ('items_to_bring', models.TextField(blank=True, help_text='Any items parents should prepare or bring this week.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_focuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', '-week_number'],
                'indexes': [models.Index(fields=['class_name', 'academic_year'], name='communicati_class_n_6a3d80_idx')],
                'unique_together': {('class_name', 'week_number', 'academic_year')},
            },
        ),
    ]
