# Generated by Django 5.2.15 on 2026-06-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_phoneotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='communicati_phone_bc3056_idx',
            old_name='communicati_phone_6e8f0a_idx',
        ),
    ]
