# Generated by Django 5.2.15 on 2026-06-27 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_rename_communicati_phone_6e8f0a_idx_communicati_phone_bc3056_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyfocus',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyfocus',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_focus_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyfocus',
            name='reviewer_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyfocus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyfocus',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='weeklyfocus',
            index=models.Index(fields=['status'], name='communicati_status_29cc3a_idx'),
        ),
    ]
