# Generated by Django 5.2.16 on 2026-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_weeklyfocus_reviewed_at_weeklyfocus_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='preview_viewed',
            field=models.BooleanField(default=False, help_text='FR-COM-001: set True when user views the preview before sending'),
        ),
    ]
