# Generated by Django 5.2.15 on 2026-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If true, user must change password before accessing any screen.'),
        ),
    ]
