# Generated by Django 5.2.15 on 2026-06-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Date staff member left the school.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='departure_reason',
            field=models.CharField(blank=True, help_text='Reason for departure (resignation, termination, transfer, etc.).', max_length=120),
        ),
    ]
