# Generated by Django 5.2.15 on 2026-07-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_departure_date_user_departure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('head_of_school', 'Head of School (HOS)'), ('primary_hod', 'Primary HOD'), ('ecd_hod', 'ECD HOD'), ('lower_secondary_hod', 'Lower Secondary HOD'), ('admin_officer', 'Admin Officer'), ('finance_officer', 'Finance Officer'), ('teacher', 'Teacher'), ('parent', 'Parent / Guardian')], db_index=True, default='teacher', max_length=40),
        ),
    ]
