# Generated by Django 5.2.16 on 2026-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_roleconfig_user_extra_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
