# Generated by Django 5.2.18 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_roleconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleconfig',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('head_of_school', 'Head of School (HOS)'), ('primary_hod', 'Primary HOD'), ('ecd_hod', 'ECD HOD'), ('lower_secondary_hod', 'Lower Secondary HOD'), ('admin_officer', 'Admin Officer'), ('finance_officer', 'Finance Officer'), ('teacher', 'Teacher'), ('parent', 'Parent')], help_text='System role identifier from UserRole TextChoices.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('head_of_school', 'Head of School (HOS)'), ('primary_hod', 'Primary HOD'), ('ecd_hod', 'ECD HOD'), ('lower_secondary_hod', 'Lower Secondary HOD'), ('admin_officer', 'Admin Officer'), ('finance_officer', 'Finance Officer'), ('teacher', 'Teacher'), ('parent', 'Parent')], db_index=True, default='teacher', max_length=40),
        ),
    ]
