# Generated by Django 4.2.30 on 2026-05-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('social', 'Social'), ('holiday', 'Holiday / Public Holiday'), ('other', 'Other')], default='academic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_public_holiday', models.BooleanField(default=False)),
                ('notify_parents', models.BooleanField(default=True)),
                ('notify_staff', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
