# Generated by Django 5.2.15 on 2026-06-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='True if created automatically from another model (Term, PTCWindow, etc.)'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the source object if auto-generated', null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='source_model',
            field=models.CharField(blank=True, default='', help_text='Source model identifier: term, ptc, term_exam', max_length=50),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['source_model', 'source_id'], name='events_cale_source__0aee6b_idx'),
        ),
    ]
