# Generated by Django 5.2.15 on 2026-06-27 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_calendarevent_auto_generated_calendarevent_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='parent_acknowledgement_required',
            field=models.BooleanField(default=False, help_text='FR-CAL-001: requires parent acknowledgement when viewing event'),
        ),
        migrations.CreateModel(
            name='EventAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='events.calendarevent')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Acknowledgement',
                'verbose_name_plural': 'Event Acknowledgements',
                'unique_together': {('event', 'parent')},
            },
        ),
    ]
