# Generated by Django 5.2.16 on 2026-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_calendarevent_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='FR-CAL-001: past events are archived rather than deleted'),
        ),
    ]
