# Generated by Django 5.2.13 on 2026-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_no', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=20)),
                ('class_name', models.CharField(db_index=True, max_length=64)),
                ('stream_name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='students_st_last_na_3e473b_idx')],
            },
        ),
    ]
