# Generated by Django 5.2.13 on 2026-04-23 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_date_of_birth_student_gender_parentguardian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_guardians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='pdpa_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='pdpa_consent_method',
            field=models.CharField(blank=True, choices=[('in_person', 'In-person'), ('digital', 'Digital')], max_length=16),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='pdpa_consent_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='pdpa_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='preferred_invoice_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('sw', 'Swahili')], max_length=16),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies_medical',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='sibling_discount_eligible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='StudentSibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_links_a', to='students.student')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_links_b', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student_a'], name='students_st_student_660285_idx'), models.Index(fields=['student_b'], name='students_st_student_6aff7d_idx')],
                'unique_together': {('student_a', 'student_b')},
            },
        ),
    ]
