# Generated by Django 5.2.13 on 2026-05-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_parentguardian_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'date_of_birth')},
        ),
    ]
