# Generated by Django 5.2.14 on 2026-05-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentguardian',
            name='relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('step_mother', 'Step-Mother'), ('step_father', 'Step-Father'), ('grandparent', 'Grandparent'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('guardian', 'Legal Guardian'), ('emergency', 'Emergency Contact'), ('other', 'Other')], default='guardian', max_length=20),
        ),
    ]
