# Generated by Django 5.2.14 on 2026-05-21 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentguardian_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaravelParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('secondary_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('laravel_parent_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLaravelParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('step_mother', 'Step-Mother'), ('step_father', 'Step-Father'), ('grandparent', 'Grandparent'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('guardian', 'Legal Guardian'), ('emergency', 'Emergency Contact'), ('other', 'Other')], default='guardian', max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('can_pickup', models.BooleanField(default=True)),
                ('emergency_contact', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='laravel_student_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['laravel_student_id'], name='students_st_laravel_097dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['qr_code'], name='students_st_qr_code_64654b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'class_name'], name='students_st_status_f7e598_idx'),
        ),
        migrations.AddField(
            model_name='laravelparent',
            name='guardian',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laravel_parent', to='students.parentguardian'),
        ),
        migrations.AddField(
            model_name='studentlaravelparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.laravelparent'),
        ),
        migrations.AddField(
            model_name='studentlaravelparent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laravel_parents', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='laravelparent',
            index=models.Index(fields=['phone'], name='students_la_phone_29787a_idx'),
        ),
        migrations.AddIndex(
            model_name='laravelparent',
            index=models.Index(fields=['laravel_parent_id'], name='students_la_laravel_4eddd3_idx'),
        ),
        migrations.AddIndex(
            model_name='laravelparent',
            index=models.Index(fields=['last_name', 'first_name'], name='students_la_last_na_b38c54_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlaravelparent',
            index=models.Index(fields=['student', 'is_primary_contact'], name='students_st_student_e87c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlaravelparent',
            index=models.Index(fields=['parent', 'can_pickup'], name='students_st_parent__6db88b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentlaravelparent',
            unique_together={('student', 'parent')},
        ),
    ]
