# Generated by Django 5.2.15 on 2026-06-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_gradeclass_sort_order'),
        ('students', '0006_laravelparent_studentlaravelparent_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicyear'),
        ),
    ]
