# Generated by Django 5.2.15 on 2026-06-25 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDPAConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('given', 'Consent Given'), ('withdrawn', 'Consent Withdrawn'), ('updated', 'Consent Updated')], max_length=16)),
                ('method', models.CharField(blank=True, choices=[('in_person', 'In-person'), ('digital', 'Digital')], max_length=16)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('previous_version', models.CharField(blank=True, help_text='Version before this change, if any', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='students.parentguardian')),
            ],
            options={
                'verbose_name': 'PDPA Consent Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
