# Generated by Django 5.2.15 on 2026-06-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_increase_lessonplanattachment_file_max_length'),
        ('students', '0008_pdpaconsentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(db_index=True, max_length=64)),
                ('stream_name', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('enrolled', 'Enrolled'), ('promoted', 'Promoted'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='enrolled', help_text='What triggered this enrollment record.', max_length=20)),
                ('enrolled_at', models.DateField(auto_now_add=True, help_text='Date this enrollment record was created.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this enrollment change.')),
                ('academic_year', models.ForeignKey(blank=True, help_text='Academic year this assignment applied to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_history', to='students.student')),
                ('term', models.ForeignKey(blank=True, help_text='Term this assignment applied to (null for year-long assignments).', null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'verbose_name': 'Enrollment History',
                'verbose_name_plural': 'Enrollment Histories',
                'ordering': ['-enrolled_at', '-created_at'],
                'indexes': [models.Index(fields=['student', 'class_name'], name='students_en_student_fb919c_idx'), models.Index(fields=['student', 'academic_year'], name='students_en_student_dc31c6_idx')],
            },
        ),
    ]
