# Generated by Django 5.2.15 on 2026-07-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_progressionconfig_progressioncase'),
        ('students', '0009_enrollment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenthistory',
            name='progression_case',
            field=models.ForeignKey(blank=True, help_text='Link to the progression case that produced this enrollment action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.progressioncase'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='action',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('promoted', 'Promoted'), ('retained', 'Retained'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='enrolled', help_text='What triggered this enrollment record.', max_length=20),
        ),
    ]
