# Generated by Django 5.2.15 on 2026-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_enrollmenthistory_progression_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='action',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('promoted', 'Promoted'), ('retained', 'Retained'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='enrolled', help_text="What triggered this enrollment record. NOTE: Historical rows where action='promoted' may represent retentions from the old CLI script — the note field should be checked for 'Repeating' to distinguish actual promotions from retentions prior to this module's launch.", max_length=20),
        ),
    ]
