# Generated by Django 5.2.15 on 2026-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_enrollmenthistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentguardian',
            name='relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('parent', 'Parent'), ('step_mother', 'Step-Mother'), ('step_father', 'Step-Father'), ('grandparent', 'Grandparent'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('guardian', 'Legal Guardian'), ('emergency', 'Emergency Contact'), ('other', 'Other')], default='guardian', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentlaravelparent',
            name='relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('parent', 'Parent'), ('step_mother', 'Step-Mother'), ('step_father', 'Step-Father'), ('grandparent', 'Grandparent'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('guardian', 'Legal Guardian'), ('emergency', 'Emergency Contact'), ('other', 'Other')], default='guardian', max_length=20),
        ),
    ]
