# Generated by Django 5.2.16 on 2026-08-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentguardian_relationship_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentguardian',
            unique_together={('full_name', 'phone')},
        ),
    ]
