# Generated by Django 5.2.15 on 2026-09-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_parentguardian_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('medical_record', 'Medical Record'), ('transfer_slip', 'Transfer Slip'), ('report_card', 'Report Card'), ('fee_receipt', 'Fee Receipt'), ('other', 'Other')], default='other', max_length=32)),
                ('file', models.FileField(max_length=255, upload_to='student_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['student', 'document_type'], name='students_st_student_7712b0_idx')],
            },
        ),
    ]
