# Generated by Django 5.2.18 on 2026-10-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studentdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
