# Generated by Django 5.2.14 on 2026-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(default='Hodari Christian School', max_length=100)),
                ('attendance_threshold_warn', models.PositiveIntegerField(default=85, help_text='Attendance % below which a warning is triggered.')),
                ('attendance_threshold_critical', models.PositiveIntegerField(default=75, help_text='Attendance % below which critical alert is triggered.')),
                ('admission_fee', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('enable_online_inquiry', models.BooleanField(default=True)),
                ('send_absentee_sms', models.BooleanField(default=True, help_text='Automatically send SMS to parents when student is marked absent.')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_sender_id', models.CharField(default='HODARI', max_length=20)),
                ('pass_mark', models.PositiveIntegerField(default=50)),
                ('enable_auto_report_generation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
