# Generated by Django 5.2.15 on 2026-06-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='default_from_email',
            field=models.EmailField(default='noreply@hodari.ac.tz', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_backend',
            field=models.CharField(default='django.core.mail.backends.console.EmailBackend', help_text="Django email backend. Use 'django.core.mail.backends.smtp.EmailBackend' for real SMTP.", max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='whatsapp_sender_id',
            field=models.CharField(blank=True, default='HODARI', max_length=30),
        ),
    ]
