# Generated by Django 5.2.15 on 2026-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_email_whatsapp_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('lesson_plans', 'Lesson Plan Attachments'), ('student_photos', 'Student Photos'), ('admission_photos', 'Admission Photos'), ('admission_documents', 'Admission Documents'), ('staff_documents', 'Staff Documents'), ('staff_leave', 'Staff Leave Documents'), ('profile_photos', 'User Profile Photos'), ('finance_imports', 'Finance Imports (CSV)')], max_length=32, unique=True)),
                ('allowed_extensions', models.CharField(default='pdf,doc,docx,xls,xlsx,csv,ppt,pptx,jpg,jpeg,png,gif,webp,svg,txt', help_text='Comma-separated file extensions (without dots).', max_length=500)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Maximum single file size in MB.')),
                ('max_total_size_mb', models.PositiveIntegerField(default=50, help_text='Maximum combined size for all files in one upload (MB).')),
                ('max_files', models.PositiveIntegerField(default=5, help_text='Maximum number of files per upload.')),
                ('duplicate_check', models.BooleanField(default=True, help_text='Reject uploads that duplicate an existing file (by name + size).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Media Settings',
                'verbose_name_plural': 'Media Settings',
                'ordering': ['area'],
            },
        ),
    ]
