# Generated by Django 5.2.15 on 2026-06-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_media_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasettings',
            name='min_height',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Minimum image height in pixels (0 = no limit).'),
        ),
        migrations.AddField(
            model_name='mediasettings',
            name='min_width',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Minimum image width in pixels (0 = no limit).'),
        ),
    ]
