# Generated by Django 5.2.15 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_media_dimension_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='pwa_domain',
            field=models.URLField(default='https://hodari.nguzo.co.tz:8443', help_text='Base URL for the Attendance PWA app. Change this when the domain changes.', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='pwa_version',
            field=models.PositiveIntegerField(default=1, help_text='Increment to force PWA cache refresh for all users.'),
        ),
    ]
