# Generated by Django 5.2.16 on 2026-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolsettings_pwa_domain_schoolsettings_pwa_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('student', 'Student Records'), ('parent', 'Parent / Guardian Records'), ('staff', 'Staff Records'), ('attendance', 'Attendance Records'), ('finance', 'Financial Records'), ('welfare', 'Welfare Records'), ('discipline', 'Discipline Records'), ('admission', 'Admission Records')], max_length=20, unique=True)),
                ('retention_years', models.PositiveIntegerField(default=7, help_text='Number of years to retain archived records before eligible for deletion.')),
                ('warning_days', models.PositiveIntegerField(default=90, help_text='Days before retention limit to send warning notifications.')),
                ('auto_prune', models.BooleanField(default=False, help_text='If True, Celery task will automatically delete records past retention. If False, only warnings are sent.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_pruned_at', models.DateTimeField(blank=True, null=True)),
                ('last_warning_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archive Retention Policy',
                'verbose_name_plural': 'Archive Retention Policies',
                'ordering': ['category'],
            },
        ),
    ]
