# Generated by Django 5.2.15 on 2026-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_archiveretentionpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='admissions_email',
            field=models.EmailField(blank=True, default='admissions@hodari.ac.tz', help_text='Reply-to address for admissions emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='admissions_phone',
            field=models.CharField(blank=True, default='+255 700 000 000', help_text='Phone number shown in admissions emails and SMS.', max_length=32),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='admissions_whatsapp',
            field=models.CharField(blank=True, default='+255 700 000 000', help_text='WhatsApp number for proof-of-payment submissions.', max_length=32),
        ),
    ]
