# Generated by Django 5.2.15 on 2026-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='login_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image shown on the left panel of the login page. Recommended: 800x900px.', null=True, upload_to='branding/login/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_logo',
            field=models.ImageField(blank=True, help_text='Logo shown on the login form. Falls back to default school logo if empty.', null=True, upload_to='branding/login/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_tagline',
            field=models.CharField(blank=True, default='', help_text='Tagline shown below the logo on the login page.', max_length=255),
        ),
    ]
