# Generated by Django 5.2.15 on 2026-08-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_login_branding_fields'),
        ('core', '0009_add_new_email_template_types'),
    ]

    operations = [
    ]
