# Generated by Django 5.2.15 on 2026-08-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260821_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='login_description',
            field=models.CharField(blank=True, default='', help_text='Description text below the heading on the left panel.', max_length=500),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_feature1',
            field=models.CharField(blank=True, default='', help_text='First feature bullet on the left panel.', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_feature2',
            field=models.CharField(blank=True, default='', help_text='Second feature bullet on the left panel.', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_feature3',
            field=models.CharField(blank=True, default='', help_text='Third feature bullet on the left panel.', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_heading',
            field=models.CharField(blank=True, default='', help_text="Main heading on the left panel. Default: 'Welcome back to {school_name}'.", max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_right_heading',
            field=models.CharField(blank=True, default='', help_text="Heading on the right panel (login form). Default: 'Sign in to your account'.", max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_right_subtitle',
            field=models.CharField(blank=True, default='', help_text='Subtitle below the heading on the right panel.', max_length=300),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='login_tagline',
            field=models.CharField(blank=True, default='', help_text='Tagline shown below the logo on the left panel.', max_length=255),
        ),
    ]
