# Generated by Django 5.2.15 on 2026-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_login_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='login_parent_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image shown when Parent tab is active. Falls back to login_hero_image.', null=True, upload_to='branding/login/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='login_staff_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image shown when Staff tab is active. Falls back to login_hero_image.', null=True, upload_to='branding/login/'),
        ),
    ]
