# Generated by Django 5.2.15 on 2026-08-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_staff_parent_hero_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='assessment_fee',
            field=models.DecimalField(decimal_places=2, default=30000.0, help_text='Assessment fee amount in TSh. Set by finance, not editable by admissions staff.', max_digits=10),
        ),
    ]
