# Generated by Django 5.2.15 on 2026-08-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_assessment_fee_to_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('activation', 'Staff Account Activation'), ('password_reset', 'Password Reset'), ('onboarding_complete', 'Onboarding Complete'), ('parent_portal', 'Parent Portal Account'), ('admission_inquiry', 'Admissions Inquiry Acknowledgement'), ('admission_meeting', 'Admissions Meeting Scheduled'), ('admission_denied', 'Admissions Application Denied'), ('admission_offer_letter', 'Admission Offer Letter'), ('admission_meeting_rescheduled', 'Meeting Rescheduled'), ('admission_assessment_logistics', 'Assessment Logistics'), ('admission_assessment_reminder', 'Assessment Reminder'), ('admission_fee_invoice', 'Admission Fee Invoice'), ('admission_document_received', 'Document Received'), ('admission_waitlist', 'Waitlist Notification'), ('admission_assessment_fee_reminder', 'Assessment Fee Reminder'), ('admission_report_reminder', 'Report Reminder'), ('admission_form_reminder', 'Form Reminder'), ('admission_invoice_reminder', 'Invoice Reminder'), ('admission_declined_at_meeting', 'Declined at Meeting'), ('admission_assessment_fee_invoice', 'Assessment Scheduled + Fee Due'), ('admission_report_submitted_hos', 'Report Submitted to HOS'), ('admission_welcome', 'Welcome / Enrolment Confirmed'), ('admission_meeting_reminder_48h', 'Meeting Reminder (48h)'), ('admission_meeting_reminder_24h', 'Meeting Reminder (24h)'), ('admission_hos_review_reminder', 'HOS Review Reminder (72h)'), ('admission_payment_receipt', 'Payment Receipt'), ('fee_invoice', 'Fee Invoice'), ('fee_reminder', 'Fee Payment Reminder'), ('checkin_notification', 'Attendance Check-in Notification'), ('checkout_notification', 'Attendance Check-out Notification'), ('otp_code', 'OTP Code'), ('broadcast', 'Broadcast Message'), ('payment_received', 'Payment Received Confirmation'), ('payment_reversal', 'Payment Reversal Notice'), ('invoice_generated', 'Invoice Generated Notification'), ('leave_approved', 'Leave Request Approved'), ('leave_rejected', 'Leave Request Rejected'), ('admission_declined_at_meeting', 'Declined at Meeting'), ('admission_assessment_fee_invoice', 'Assessment Scheduled + Fee Due'), ('admission_report_submitted_hos', 'Report Submitted to HOS'), ('admission_welcome', 'Welcome / Enrolment Confirmed'), ('admission_meeting_reminder_48h', 'Meeting Reminder (48h)'), ('admission_meeting_reminder_24h', 'Meeting Reminder (24h)'), ('admission_hos_review_reminder', 'HOS Review Reminder (72h)'), ('admission_payment_receipt', 'Payment Receipt')], max_length=40, unique=True),
        ),
    ]
