# Generated by Django 5.2.15 on 2026-08-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_emailtemplate_template_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_day', models.PositiveSmallIntegerField(default=0, help_text='Day of week deadline (0=Monday, 4=Friday).')),
                ('deadline_time', models.TimeField(default='08:00', help_text='Time of day the deadline occurs.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one deadline config should be active at a time.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Plan Deadline',
                'verbose_name_plural': 'Lesson Plan Deadlines',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
