# Generated by Django 5.2.15 on 2026-08-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_lessonplandeadline'),
        ('core', '0016_lessonplandeadline'),
    ]

    operations = [
    ]
