# Generated by Django 5.2.17 on 2026-10-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260824_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='email_backend',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='email_use_tls',
        ),
    ]
