# Generated by Django 5.2.18 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_smtp_settings_moved_to_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveretentionpolicy',
            name='category',
            field=models.CharField(choices=[('student', 'Student Records'), ('parent', 'Parent Records'), ('staff', 'Staff Records'), ('attendance', 'Attendance Records'), ('finance', 'Financial Records'), ('welfare', 'Welfare Records'), ('discipline', 'Discipline Records'), ('admission', 'Admission Records')], max_length=20, unique=True),
        ),
    ]
