# Generated by Django 5.2.14 on 2026-05-27 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoice_reminder_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('salary', 'Salaries & Wages'), ('utilities', 'Utilities (Water, Electricity, Internet)'), ('supplies', 'School Supplies & Materials'), ('maintenance', 'Maintenance & Repairs'), ('transport', 'Transport & Fuel'), ('catering', 'Catering & Meals'), ('events', 'Events & Activities'), ('professional', 'Professional Services'), ('rent', 'Rent & Lease'), ('technology', 'Technology & Software'), ('marketing', 'Marketing & Advertising'), ('insurance', 'Insurance'), ('tax', 'Taxes & Licenses'), ('other', 'Other')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money')], default='cash', max_length=30)),
                ('reference', models.CharField(blank=True, help_text='Receipt or invoice reference', max_length=120)),
                ('vendor', models.CharField(blank=True, help_text='Payee or vendor name', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_reimbursement', models.BooleanField(default=False, help_text='Is this a reimbursement to staff?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
