# Generated by Django 5.2.14 on 2026-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='assessment_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Assessment fee used by Admissions pipeline (TZS)', max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='late_pickup_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late pickup charge per instance (TZS)', max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='sibling_discount_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=12),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='sibling_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount — interpret as percentage or fixed TZS based on mode', max_digits=10),
        ),
    ]
