# Generated by Django 5.2.14 on 2026-05-27 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subject_classes'),
        ('finance', '0010_payment_notes_payment_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='academics.term'),
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('salary', 'Salaries & Wages'), ('utilities', 'Utilities (Water, Electricity, Internet)'), ('supplies', 'School Supplies & Materials'), ('maintenance', 'Maintenance & Repairs'), ('transport', 'Transport & Fuel'), ('catering', 'Catering & Meals'), ('events', 'Events & Activities'), ('professional', 'Professional Services'), ('rent', 'Rent & Lease'), ('technology', 'Technology & Software'), ('marketing', 'Marketing & Advertising'), ('insurance', 'Insurance'), ('tax', 'Taxes & Licenses'), ('other', 'Other')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('termly', 'Per Term'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money')], default='bank_transfer', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('next_due_date', models.DateField(db_index=True)),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Expense',
                'verbose_name_plural': 'Recurring Expenses',
                'ordering': ['next_due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('salary', 'Salaries & Wages'), ('utilities', 'Utilities (Water, Electricity, Internet)'), ('supplies', 'School Supplies & Materials'), ('maintenance', 'Maintenance & Repairs'), ('transport', 'Transport & Fuel'), ('catering', 'Catering & Meals'), ('events', 'Events & Activities'), ('professional', 'Professional Services'), ('rent', 'Rent & Lease'), ('technology', 'Technology & Software'), ('marketing', 'Marketing & Advertising'), ('insurance', 'Insurance'), ('tax', 'Taxes & Licenses'), ('other', 'Other')], db_index=True, max_length=30)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Budgeted amount (TZS)', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('is_frozen', models.BooleanField(default=False, help_text='Lock budget once approved')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='academics.term')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('term', 'category')},
            },
        ),
    ]
