# Generated by Django 5.2.14 on 2026-05-27 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subject_classes'),
        ('finance', '0011_expense_approved_at_expense_approved_by_and_more'),
        ('students', '0006_laravelparent_studentlaravelparent_student_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concession_type', models.CharField(choices=[('sibling', 'Sibling Discount'), ('merit', 'Merit Scholarship'), ('financial_aid', 'Financial Aid'), ('staff', 'Staff Concession'), ('need_based', 'Needs-Based Concession'), ('other', 'Other')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Reason or description for the concession', max_length=255)),
                ('discount_mode', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed TZS amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this concession')),
                ('valid_from', models.DateField(blank=True, help_text='Optional start date for concession validity', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Optional end date for concession validity', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_concessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_concessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='academics.term')),
            ],
            options={
                'verbose_name': 'Concession',
                'verbose_name_plural': 'Concessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
