# Generated by Django 5.2.14 on 2026-05-27 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_concession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_fee_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('locked', 'Locked')], db_index=True, default='draft', help_text='Draft=editable, Published=visible to invoicing, Locked=read-only', max_length=12),
        ),
        migrations.CreateModel(
            name='ReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable auto-reminder system')),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('every_3_days', 'Every 3 Days'), ('custom', 'Custom Schedule')], default='weekly', max_length=20)),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both Email & SMS')], default='email', max_length=10)),
                ('first_reminder_days', models.PositiveIntegerField(default=7, help_text='Days after due date for first reminder')),
                ('second_reminder_days', models.PositiveIntegerField(default=14, help_text='Days after due date for second reminder')),
                ('final_reminder_days', models.PositiveIntegerField(default=30, help_text='Days after due date for final/escalation reminder')),
                ('reminder_template_sms', models.TextField(blank=True, help_text='SMS template. Use {{student_name}}, {{balance}}, {{due_date}}')),
                ('reminder_template_email', models.TextField(blank=True, help_text='Email template. Use {{student_name}}, {{balance}}, {{due_date}}')),
                ('auto_escalate_to_hos', models.BooleanField(default=False, help_text='Escalate to HOS after final reminder')),
                ('escalation_days', models.PositiveIntegerField(default=45, help_text='Days after due date for HOS escalation')),
                ('notify_finance_officer', models.BooleanField(default=True, help_text='Notify Finance Officer when reminders are sent')),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder Configuration',
                'verbose_name_plural': 'Reminder Configurations',
            },
        ),
    ]
