# Generated by Django 5.2.14 on 2026-05-27 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_feestructure_locked_at_feestructure_locked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeperiod',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Finance Period', 'verbose_name_plural': 'Finance Periods'},
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='end_date',
            field=models.DateField(blank=True, help_text='Period end date', null=True),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this period'),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_finance_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='start_date',
            field=models.DateField(blank=True, help_text='Period start date', null=True),
        ),
        migrations.AlterField(
            model_name='financeperiod',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text='Lock period once reconciled'),
        ),
        migrations.CreateModel(
            name='FinanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_currency', models.CharField(default='TZS', help_text='Default currency code', max_length=10)),
                ('fiscal_year_start', models.DateField(blank=True, help_text='Start of the fiscal year', null=True)),
                ('fiscal_year_end', models.DateField(blank=True, help_text='End of the fiscal year', null=True)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Default invoice number prefix', max_length=10)),
                ('invoice_due_days', models.PositiveIntegerField(default=30, help_text='Default days until invoice due')),
                ('invoice_terms', models.TextField(blank=True, help_text='Default invoice terms and conditions')),
                ('default_payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('mpesa', 'M-Pesa'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reminder_grace_days', models.PositiveIntegerField(default=7, help_text='Days after due date before reminders start')),
                ('auto_reminder_enabled', models.BooleanField(default=False, help_text='Enable automated fee reminders')),
                ('finance_officer_email', models.EmailField(blank=True, help_text='Email for finance notifications', max_length=254)),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Late fee as percentage of outstanding (e.g. 5 = 5%)', max_digits=5)),
                ('late_fee_max_days', models.PositiveIntegerField(default=90, help_text='Maximum days to apply late fee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Configuration',
                'verbose_name_plural': 'Finance Configuration',
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_type', models.CharField(choices=[('invoice', 'Invoice / Receivable'), ('payment', 'Payment / Cash'), ('expense', 'Expense / Payable'), ('bank', 'Bank Balance'), ('other', 'Other')], db_index=True, default='invoice', max_length=12)),
                ('description', models.CharField(help_text='Description of this opening balance entry', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Opening balance amount (TZS)', max_digits=14)),
                ('is_debit', models.BooleanField(default=True, help_text='True=debit (asset), False=credit (liability)')),
                ('reference', models.CharField(blank=True, help_text='Optional reference document or invoice', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_entries', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.financeperiod')),
            ],
            options={
                'verbose_name': 'Opening Balance',
                'verbose_name_plural': 'Opening Balances',
                'ordering': ['-period__start_date', 'balance_type'],
            },
        ),
    ]
