# Generated by Django 4.2.27 on 2026-05-01 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_parentguardian_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('low', 'Low — general observation'), ('medium', 'Medium — requires monitoring'), ('high', 'High — HOD follow-up required'), ('critical', 'Critical — immediate escalation')], db_index=True, default='low', max_length=10)),
                ('observation_date', models.DateField(db_index=True)),
                ('observation_text', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('hod_status', models.CharField(blank=True, choices=[('pending', 'Pending review'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('hod_notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_observations', to='students.student')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observation_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'observation_date'], name='welfare_wel_student_4c496a_idx'), models.Index(fields=['severity', 'hod_status'], name='welfare_wel_severit_ad3d1e_idx')],
            },
        ),
    ]
