# Generated by Django 5.2.14 on 2026-05-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0002_add_welfare_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfareobservation',
            name='concern_type',
            field=models.CharField(choices=[('behavioral', 'Behavioral'), ('health', 'Health'), ('attendance', 'Attendance'), ('academic', 'Academic'), ('home_situation', 'Home situation'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
