# Generated by Django 5.2.14 on 2026-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0004_discipline_modernization'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfareobservation',
            name='parent_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='parent_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
