# Generated by Django 5.2.15 on 2026-06-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0005_welfareobservation_parent_confirmation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welfareobservation',
            name='actions_taken_detailed',
        ),
        migrations.RemoveField(
            model_name='welfareobservation',
            name='incident_level_1',
        ),
        migrations.RemoveField(
            model_name='welfareobservation',
            name='incident_level_2',
        ),
        migrations.RemoveField(
            model_name='welfareobservation',
            name='incident_level_3',
        ),
        migrations.RemoveField(
            model_name='welfareobservation',
            name='incident_level_4',
        ),
        migrations.RemoveField(
            model_name='welfareobservation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='welfareobservation',
            name='previous_incidents',
        ),
        migrations.RemoveField(
            model_name='welfareobservation',
            name='time_of_incident',
        ),
    ]
