# Generated by Django 5.2.15 on 2026-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0006_remove_discipline_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfareobservation',
            name='severity',
            field=models.CharField(choices=[('low', 'Low (general observation)'), ('medium', 'Medium (requires monitoring)'), ('high', 'High (HOD follow-up required)'), ('critical', 'Critical (immediate escalation)')], db_index=True, default='low', max_length=10),
        ),
    ]
