# Generated by Django 5.2.15 on 2026-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0007_alter_welfareobservation_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfareobservation',
            name='parent_signature_name',
            field=models.CharField(blank=True, help_text='Name of parent/guardian who signed', max_length=255),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='parent_signed',
            field=models.BooleanField(default=False, help_text='Whether parent/guardian has signed the welfare report'),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='parent_signed_at',
            field=models.DateTimeField(blank=True, help_text='When parent/guardian signed', null=True),
        ),
    ]
