# Generated by Django 5.2.15 on 2026-07-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0010_add_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='welfareobservation',
            name='idx_wei_hod_status',
        ),
        migrations.RemoveIndex(
            model_name='welfareobservation',
            name='idx_wei_submitted_by',
        ),
    ]
