# Generated by Django 5.2.15 on 2026-08-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0011_remove_welfareobservation_idx_wei_hod_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welfareobservation',
            options={'ordering': ['-observation_date', '-created_at'], 'permissions': [('can_review_observation', 'Can review and approve welfare observations')]},
        ),
    ]
