# Generated by Django 5.2.17 on 2026-09-27 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_note_type(apps, schema_editor):
    """Existing notes never stored a type: the UI inferred it from severity,
    which is how Health/Behaviour notes ended up displayed as Positive.
    Recover the type the old form actually submitted:
      safeguarding -> critical + concern_type "other"
      concern      -> medium/high/critical
      positive     -> low + concern_type "other"
      observation  -> everything else
    and stamp submitted_at from created_at."""
    Obs = apps.get_model("welfare", "WelfareObservation")
    for obs in Obs.objects.all().only("id", "severity", "concern_type", "created_at"):
        if obs.severity == "critical" and obs.concern_type == "other":
            note_type = "safeguarding"
        elif obs.severity in ("medium", "high", "critical"):
            note_type = "concern"
        elif obs.concern_type == "other":
            note_type = "positive"
        else:
            note_type = "observation"
        tags = ["Health"] if obs.concern_type == "health" else []
        Obs.objects.filter(pk=obs.pk).update(
            note_type=note_type, tags=tags, submitted_at=obs.created_at,
            is_locked=(note_type == "safeguarding"),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0012_alter_welfareobservation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welfareobservation',
            options={'ordering': ['-observation_date', '-created_at'], 'permissions': [('can_review_observation', 'Can review and approve welfare observations'), ('view_safeguarding_note', 'Can view safeguarding notes (Safeguarding Lead)')]},
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='follow_up_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='welfare.welfareobservation'),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='note_type',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('observation', 'Observation'), ('concern', 'Concern'), ('safeguarding', 'Safeguarding')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], db_index=True, default='submitted', max_length=10),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfareobservation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WelfareObservationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('changes', models.JSONField(default=dict)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_revisions', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='welfare.welfareobservation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(backfill_note_type, migrations.RunPython.noop),
    ]
