# Generated by Django 5.2.17 on 2026-09-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0013_note_type_drafts_revisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welfareobservation',
            options={'ordering': ['-observation_date', '-created_at'], 'permissions': [('can_review_observation', 'Can review and approve welfare observations'), ('view_safeguarding_note', 'Can view safeguarding notes (a child may be at risk of harm)')]},
        ),
    ]
