# Generated by Django 5.2.18 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0015_grant_safeguarding_to_head_of_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfareobservation',
            name='parent_signature_name',
            field=models.CharField(blank=True, help_text='Name of parent who signed', max_length=255),
        ),
        migrations.AlterField(
            model_name='welfareobservation',
            name='parent_signed',
            field=models.BooleanField(default=False, help_text='Whether parent has signed the welfare report'),
        ),
        migrations.AlterField(
            model_name='welfareobservation',
            name='parent_signed_at',
            field=models.DateTimeField(blank=True, help_text='When parent signed', null=True),
        ),
    ]
