from django.urls import path

from academics.views import (
    DuplicateCheckView,
    GradeClassListView,
    GradeClassEditView,
    GradeClassDeleteView,
    LessonPlanCreateView,
    LessonPlanUpdateView,
    LessonPlanDeleteView,
    LessonPlanListView,
    LessonPlanComplianceView,
    LessonPlanReviewView,
    LessonPlanSubmitView,
    LessonPlanWithdrawView,
    LessonPlanAttachmentDeleteView,
    LessonPlanProgressView,
    LessonPlanReviewQueueView,
    LessonPlanReportsView,
    QuickLessonPlanView,
    LessonPlanWithdrawModalView,
    LessonPlanEditModalView,
    ExamScoreEntryView,
    HOSSignOffListView,
    HOSReportPreviewView,
    HOSSignOffActionView,
    ReportReviewQueueView,
    ParentReportListView,
    ReportRouterView,
    AcademicAnalyticsView,
    AtRiskStudentsListView,
    ExamScoreCorrectionView,
    ExamScoreApprovalQueueView,
    ECDEvaluationEntryView,
    CambridgeCheckpointEntryView,
    RoomListView,
    RoomEditView,
    RoomDeleteView,
    AcademicReportExportView,
    ECDStudentsAPIView,
    ECDEvaluationAPIView,
    ECDSubmissionAPIView,
    ECDProgressAPIView,
    ECDAssessmentView,
    PrimaryCommentEntryView,
    ScoreCorrectionHistoryView,
    ReportCardListView,
    PrimaryScoreEntryView,
    PrimaryStudentsAPIView,
    PrimaryScoreAPIView,
    PrimaryBulkSubmissionAPIView,
    LowerSecondaryScoreEntryView,
    LowerSecondaryStudentsAPIView,
    LowerSecondaryScoreAPIView,
    LowerSecondaryBulkSubmissionAPIView,
    MigrationTriggerView,
    SubjectListView,
    SubjectEditView,
    SubjectDeleteView,
    SubjectsPerGradeView,
    SubjectClassesAPIView,
    ECDDomainConfigListView,
    ReportPDFDownloadView,
    StudentAcademicRecordView,
    ProgressionConfigListView,
    ProgressionConfigEditView,
    ProgressionConfigDeleteView,
    ProgressionCaseCalculateView,
    ProgressionHODReviewListView,
    ProgressionHODReviewActionView,
    ProgressionHODBulkApproveView,
    ProgressionHOSDecisionListView,
    ProgressionHOSDecisionActionView,
    ProgressionHOSBulkDecideView,
    ProgressionBulkPromotionView,
    ProgressionExecutePromotionView,
    ProgressionTeacherView,
    ProgressionParentView,
    PrintProgressionOutcomeView,
)

app_name = "academics"


urlpatterns = [
    path("lesson-plans/", LessonPlanListView.as_view(), name="lesson_plans"),
    path("lesson-plans/new/", LessonPlanCreateView.as_view(), name="new_lesson_plan"),
    path("lesson-plans/<int:pk>/edit/", LessonPlanUpdateView.as_view(), name="lesson_plan_edit"),
    path("lesson-plans/<int:pk>/submit/", LessonPlanSubmitView.as_view(), name="submit_lesson_plan"),
    path("lesson-plans/<int:pk>/delete/", LessonPlanDeleteView.as_view(), name="delete_lesson_plan"),
    path("lesson-plans/<int:pk>/withdraw/", LessonPlanWithdrawView.as_view(), name="withdraw_lesson_plan"),
    path("lesson-plans/<int:pk>/review/", LessonPlanReviewView.as_view(), name="review_lesson_plan"),
    path("exam-scores/", ExamScoreEntryView.as_view(), name="exam_scores_entry"),
    path("exam-scores/<int:pk>/correct/", ExamScoreCorrectionView.as_view(), name="exam_score_correction"),
    path("analytics/", AcademicAnalyticsView.as_view(), name="analytics"),
    path("analytics/at-risk/", AtRiskStudentsListView.as_view(), name="at_risk_list"),

    path("reports/", ReportRouterView.as_view(), name="reports_router"),
    path("hos-signoff/", HOSSignOffListView.as_view(), name="hos_signoff_list"),
    path("reports/hos-signoff/", HOSSignOffListView.as_view(), name="hos_signoff_list_legacy"),
    path("reports/list/", ReportCardListView.as_view(), name="report_card_list"),

    path("reports/<int:pk>/preview/", HOSReportPreviewView.as_view(), name="report_preview"),
    path("reports/signoff/action/", HOSSignOffActionView.as_view(), name="signoff_action"),
    path("reports/parent/", ParentReportListView.as_view(), name="parent_reports"),
    path("ecd-evaluations/", ECDEvaluationEntryView.as_view(), name="ecd_evaluations_entry"),
    # Rooms
    path("rooms/", RoomListView.as_view(), name="rooms"),
    path("rooms/<int:pk>/edit/", RoomEditView.as_view(), name="room_edit"),
    path("rooms/<int:pk>/delete/", RoomDeleteView.as_view(), name="room_delete"),
    path("reports/export/", AcademicReportExportView.as_view(), name="export_academic_report"),
    
    # ECD Assessment API Endpoints
    path("api/ecd/students/", ECDStudentsAPIView.as_view(), name="api_ecd_students"),
    path("api/ecd/evaluation/<int:student_id>/", ECDEvaluationAPIView.as_view(), name="api_ecd_evaluation"),
    path("api/ecd/submit/<int:student_id>/", ECDSubmissionAPIView.as_view(), name="api_ecd_submit"),
    path("api/ecd/progress/", ECDProgressAPIView.as_view(), name="api_ecd_progress"),
    path("ecd-assessment/", ECDAssessmentView.as_view(), name="ecd_assessment"),
    path("primary-comments/", PrimaryCommentEntryView.as_view(), name="primary_comments_entry"),
    path("correction-history/", ScoreCorrectionHistoryView.as_view(), name="score_correction_history"),
    path("primary-assessment/", PrimaryScoreEntryView.as_view(), name="primary_assessment"),
    path("api/primary/students/", PrimaryStudentsAPIView.as_view(), name="api_primary_students"),
    path("api/primary/scores/<int:student_id>/", PrimaryScoreAPIView.as_view(), name="api_primary_scores"),
    path("api/primary/submit-all/", PrimaryBulkSubmissionAPIView.as_view(), name="api_primary_submit_all"),
    path("lower-secondary-assessment/", LowerSecondaryScoreEntryView.as_view(), name="lower_secondary_assessment"),
    path("api/lower-secondary/students/", LowerSecondaryStudentsAPIView.as_view(), name="api_lower_secondary_students"),
    path("api/lower-secondary/scores/<int:student_id>/", LowerSecondaryScoreAPIView.as_view(), name="api_lower_secondary_scores"),
    path("api/lower-secondary/submit-all/", LowerSecondaryBulkSubmissionAPIView.as_view(), name="api_lower_secondary_submit_all"),
    path("force-migrate/", MigrationTriggerView.as_view(), name="force_migrate"),

    # Subjects
    path("classes/", GradeClassListView.as_view(), name="class_management"),
    path("classes/<int:pk>/edit/", GradeClassEditView.as_view(), name="class_edit"),
    path("classes/<int:pk>/delete/", GradeClassDeleteView.as_view(), name="class_delete"),

    path("subjects/", SubjectListView.as_view(), name="subjects"),
    path("subjects/per-grade/", SubjectsPerGradeView.as_view(), name="subjects_per_grade"),
    path("subjects/<int:pk>/edit/", SubjectEditView.as_view(), name="subject_edit"),
    path("subjects/<int:pk>/edit-json/", SubjectEditView.as_view(), name="subject_edit_json"),
    path("subjects/<int:pk>/delete/", SubjectDeleteView.as_view(), name="subject_delete"),
    path("api/subjects-by-class/", SubjectClassesAPIView.as_view(), name="api_subjects_by_class"),

    # ECD Domain Configuration
    path("ecd-domains/", ECDDomainConfigListView.as_view(), name="ecd_domain_config"),

    # Cambridge Checkpoint (FR-ACAD-005)
    path("exam-score-approval-queue/", ExamScoreApprovalQueueView.as_view(), name="exam_score_approval_queue"),
    path("cambridge-checkpoint/", CambridgeCheckpointEntryView.as_view(), name="cambridge_checkpoint_entry"),

    # Report PDF Download (server-side PDF via weasyprint)
    path("reports/<int:pk>/download/", ReportPDFDownloadView.as_view(), name="report_pdf_download"),

    path("duplicate-check/", DuplicateCheckView.as_view(), name="duplicate_check"),
    path("lesson-plans/progress/", LessonPlanProgressView.as_view(), name="lesson_plan_progress"),
    path("lesson-plans/review-queue/", LessonPlanReviewQueueView.as_view(), name="lesson_plan_review_queue"),
    path("lesson-plans/reports/", LessonPlanReportsView.as_view(), name="lesson_plan_reports"),
    path("lesson-plans/compliance/", LessonPlanComplianceView.as_view(), name="lesson_plan_compliance"),
    path("lesson-plans/attachments/<int:pk>/delete/", LessonPlanAttachmentDeleteView.as_view(), name="attachment_delete"),
    path("lesson-plans/quick-create/", QuickLessonPlanView.as_view(), name="quick_lesson_plan"),
    path("lesson-plans/<int:pk>/withdraw-modal/", LessonPlanWithdrawModalView.as_view(), name="withdraw_lesson_plan_modal"),
    path("lesson-plans/<int:pk>/edit-modal/", LessonPlanEditModalView.as_view(), name="edit_lesson_plan_modal"),
    path("reports/review-queue/", ReportReviewQueueView.as_view(), name="report_review_queue"),
    path("student/<int:pk>/academic-record/", StudentAcademicRecordView.as_view(), name="student_academic_record"),

    # Progression / Promotion Settings (Phase One: FR-ACAD-008)
    path("progression/config/", ProgressionConfigListView.as_view(), name="progression_config_list"),
    path("progression/config/<int:pk>/edit/", ProgressionConfigEditView.as_view(), name="progression_config_edit"),
    path("progression/config/<int:pk>/delete/", ProgressionConfigDeleteView.as_view(), name="progression_config_delete"),
    path("progression/config/<int:config_id>/calculate/", ProgressionCaseCalculateView.as_view(), name="progression_config_calculate"),

    # Phase Three — HOD Review & HOS Decision
    path("progression/hod-review/", ProgressionHODReviewListView.as_view(), name="progression_hod_review"),
    path("progression/hod-review/bulk-approve/", ProgressionHODBulkApproveView.as_view(), name="progression_hod_bulk_approve"),
    path("progression/hod-review/<int:case_id>/action/", ProgressionHODReviewActionView.as_view(), name="progression_hod_review_action"),
    path("progression/hos-decision/", ProgressionHOSDecisionListView.as_view(), name="progression_hos_decision"),
    path("progression/hos-decision/<int:case_id>/action/", ProgressionHOSDecisionActionView.as_view(), name="progression_hos_decision_action"),
    path("progression/hos-decision/bulk-decide/", ProgressionHOSBulkDecideView.as_view(), name="progression_hos_bulk_decide"),

    # Item 2 — Teacher read-only view
    path("progression/teacher/", ProgressionTeacherView.as_view(), name="progression_teacher_view"),

    # Item 3 — Parent finalized-outcome view
    path("progression/parent/", ProgressionParentView.as_view(), name="progression_parent_view"),

    # Phase Four — Bulk Promotion Execution
    path("progression/bulk-promotion/", ProgressionBulkPromotionView.as_view(), name="progression_bulk_promotion"),
    path("progression/bulk-promotion/<int:config_id>/execute/", ProgressionExecutePromotionView.as_view(), name="progression_execute_promotion"),
    path("progression/letter/", PrintProgressionOutcomeView.as_view(), name="progression_letter"),
]