# Generated by Django 5.2.13 on 2026-05-04 21:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_gradeclass_subject_reportcard_ecd_template_type_and_more'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='first_name',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='contact_email',
            field=models.EmailField(default='admin@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='contact_phone',
            field=models.CharField(default='0000000000', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('ECD', 'ECD'), ('PRIMARY', 'Primary'), ('LOWER_SECONDARY', 'Lower Secondary'), ('ADMINISTRATION', 'Administration')], default='ADMIN', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employment_start_date',
            field=models.DateField(default=datetime.date(2026, 5, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(default='Staff Member', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='period_name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects_taught', models.JSONField(default=list)),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.gradeclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.staffprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'unique_together': {('teacher', 'term', 'grade_class')},
            },
        ),
    ]
