# Generated by Django 5.2.14 on 2026-05-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_staffdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
