# Generated by Django 5.2.14 on 2026-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_staffprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Employment contract expiry; used for renewal reminders.', null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_category',
            field=models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-teaching')], default='teaching', help_text='Administration staff may be teaching or non-teaching.', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
