# Generated by Django 5.2.14 on 2026-05-27 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_onboardingchecklistitem_alter_payrollrun_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYETaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='2024/2025', help_text='Tax band version (e.g. 2024/2025)', max_length=20)),
                ('band_from', models.DecimalField(decimal_places=2, help_text='Lower bound of this band (TZS)', max_digits=12)),
                ('band_to', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound of this band (TZS). Null = infinity.', max_digits=12, null=True)),
                ('base_tax', models.DecimalField(decimal_places=2, default=0, help_text='Base tax amount for this band (cumulative from previous bands)', max_digits=12)),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='Tax rate for this band as percentage (e.g. 8.00 = 8%%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Only active bands are used for current payroll runs')),
                ('effective_from', models.DateField(blank=True, help_text='Date from which this band version applies', null=True)),
            ],
            options={
                'verbose_name': 'PAYE Tax Band',
                'verbose_name_plural': 'PAYE Tax Bands',
                'ordering': ['band_from'],
            },
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='heslb_deduction_order_ref',
            field=models.CharField(blank=True, default='', help_text='HESLB deduction order reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='heslb_deduction_start_date',
            field=models.DateField(blank=True, help_text='Date HESLB deductions should start', null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='heslb_deduction_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Basic')], default='', help_text='HESLB deduction type: fixed TZS amount or %% of basic salary', max_length=12),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='heslb_deduction_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HESLB deduction amount (TZS if fixed, percentage if percentage type)', max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='heslb_has_loan',
            field=models.BooleanField(default=False, help_text='Does this employee have an active HESLB loan?'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nssf_employee_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='NSSF employee contribution rate as percentage (e.g. 10.00 = 10%%)', max_digits=5)),
                ('nssf_employer_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='NSSF employer contribution rate as percentage (e.g. 10.00 = 10%%)', max_digits=5)),
                ('working_days_per_month', models.PositiveIntegerField(default=26, help_text='Standard working days per month for daily rate calculations')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Configuration',
                'verbose_name_plural': 'Payroll Configuration',
            },
        ),
    ]
