# Generated by Django 5.2.15 on 2026-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_payetaxband_staffprofile_heslb_deduction_order_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='national_id_number',
            field=models.CharField(blank=True, default='', help_text='NIDA or Passport number', max_length=50),
        ),
    ]
