# Generated by Django 5.2.15 on 2026-07-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_merge_20260703_0300'),
        ('hr', '0013_merge_20260706_1234'),
    ]

    operations = [
    ]
