# Generated by Django 5.2.16 on 2026-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_merge_20260703_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingchecklistitem',
            name='step',
            field=models.PositiveSmallIntegerField(help_text='Onboarding step (1-5)'),
        ),
        migrations.AlterField(
            model_name='staffonboardingprogress',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current step (1-5)'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=not started, 1-5=in progress, 6=completed'),
        ),
    ]
