# Generated by Django 5.2.15 on 2026-07-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_onboardingchecklistitem_step_and_more'),
        ('hr', '0014_merge_20260706_2343'),
    ]

    operations = [
    ]
