# Generated by Django 5.2.15 on 2026-08-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_merge_20260726_1434'),
        ('hr', '0015_teacherclassassignment_rollover_ignored'),
    ]

    operations = [
    ]
