# Generated by Django 5.2.16 on 2026-08-05 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0045_term_academic_year_protect'),
        ('hr', '0015_teacherclassassignment_rollover_ignored'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassassignment',
            name='repeat_across_terms',
            field=models.BooleanField(default=False, help_text='If True, this assignment will be automatically created for each new term until stopped.'),
        ),
        migrations.CreateModel(
            name='RolloverConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_type', models.CharField(choices=[('teacher_inactive', 'Teacher Inactive'), ('class_missing', 'Class No Longer Exists'), ('subject_conflict', 'Subject Already Assigned'), ('class_teacher_conflict', 'Class Teacher Conflict'), ('contract_expired', 'Contract Expired')], max_length=30)),
                ('conflict_detail', models.TextField(help_text='Human-readable description of the conflict.')),
                ('subjects_taught', models.JSONField(default=list)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_action', models.CharField(blank=True, choices=[('skip', 'Skip'), ('force', 'Force Create'), ('modify', 'Modified & Created')], help_text='What the admin decided to do with this conflict.', max_length=20)),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollover_conflicts', to='academics.gradeclass')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_rollover_conflicts', to=settings.AUTH_USER_MODEL)),
                ('source_assignment', models.ForeignKey(help_text='The original assignment that triggered this conflict.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollover_conflicts_from', to='hr.teacherclassassignment')),
                ('target_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollover_conflicts', to='academics.term')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollover_conflicts', to='hr.staffprofile')),
            ],
            options={
                'verbose_name': 'Rollover Conflict',
                'verbose_name_plural': 'Rollover Conflicts',
                'ordering': ['-created_at'],
            },
        ),
    ]
