# Generated by Django 5.2.15 on 2026-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_add_rollover_fields'),
        ('hr', '0016_merge_20260803_2235'),
    ]

    operations = [
    ]
