# Generated by Django 5.2.15 on 2026-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_merge_20260806_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassassignment',
            name='is_assistant_class_teacher',
            field=models.BooleanField(default=False, help_text='Is this the assistant class teacher?'),
        ),
    ]
