# Generated by Django 5.2.17 on 2026-09-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_teacherclassassignment_is_assistant_class_teacher'),
    ]

    # State-only: 0011 already drops these indexes with raw SQL (IF EXISTS), so
    # running RemoveIndex against the database again would fail on fresh DBs.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='leaveallocation',
                    name='idx_la_staff',
                ),
                migrations.RemoveIndex(
                    model_name='leaverequest',
                    name='idx_lr_staff',
                ),
                migrations.RemoveIndex(
                    model_name='teacherclassassignment',
                    name='idx_tca_teacher',
                ),
                migrations.RemoveIndex(
                    model_name='teacherclassassignment',
                    name='idx_tca_term',
                ),
            ],
        ),
    ]
