# Generated by Django 5.2.13 on 2026-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_full_name', models.CharField(max_length=150)),
                ('parent_phone', models.CharField(max_length=32)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('child_full_name', models.CharField(max_length=150)),
                ('child_date_of_birth', models.DateField()),
                ('grade_applying_for', models.CharField(max_length=32)),
                ('previous_school', models.CharField(blank=True, max_length=120)),
                ('sibling_currently_enrolled', models.BooleanField(default=False)),
                ('inquiry_channel', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone_call', 'Phone call'), ('website', 'Website form'), ('social', 'Social media referral')], max_length=20)),
                ('status', models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], db_index=True, default='inquiry_received', max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'grade_applying_for'], name='admissions__status_7dbcea_idx'), models.Index(fields=['inquiry_channel', 'created_at'], name='admissions__inquiry_57bd52_idx')],
            },
        ),
    ]
