# Generated by Django 5.2.13 on 2026-04-23 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], max_length=40)),
                ('to_status', models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='admissions.applicant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant', 'created_at'], name='admissions__applica_0e91a5_idx')],
            },
        ),
    ]
