# Generated by Django 5.2.13 on 2026-04-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_assessmentschedule_enrolmentchecklist_and_more'),
        ('students', '0002_student_date_of_birth_student_gender_parentguardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='enrolled_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_applicant', to='students.student'),
        ),
    ]
