# Generated by Django 5.2.13 on 2026-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_applicant_enrolled_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
