# Generated by Django 5.2.13 on 2026-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_seed_admission_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='parent_invoice_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sibling_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
