# Generated by Django 5.2.13 on 2026-05-04 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_applicant_parent_invoice_name_and_more'),
        ('students', '0004_alter_student_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='sibling_link_decision',
            field=models.CharField(blank=True, choices=[('linked', 'Link to existing parent'), ('new', 'Create new parent record')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sibling_matched_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_applicants', to='students.parentguardian'),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='hod_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='hod_signed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='hod_signed_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='hod_signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_hod_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='result',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional')], max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='teacher_comments',
            field=models.TextField(blank=True),
        ),
    ]
