# Generated by Django 5.2.14 on 2026-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_applicant_sibling_link_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocumentreceipt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='inquiry_channel',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('phone_call', 'Phone call'), ('website', 'Website form'), ('social', 'Social media referral')], default='walk_in', max_length=20),
        ),
    ]
