# Generated by Django 5.2.14 on 2026-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_applicantdocumentreceipt_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/photos/'),
        ),
    ]
