# Generated by Django 5.2.15 on 2026-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_alter_assessmentschedule_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='conditional_conditions',
            field=models.TextField(blank=True, help_text="Conditions for conditional admission (recorded when HOS selects 'Conditional')"),
        ),
    ]
