# Generated by Django 5.2.15 on 2026-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_applicantinternalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='parent_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='', help_text='Relationship of parent/guardian to the student.', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='previous_school_other',
            field=models.CharField(blank=True, help_text="Free-text when 'Other' is selected", max_length=120),
        ),
    ]
