# Generated by Django 5.2.16 on 2026-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_applicant_parent_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentschedule',
            name='assessment_fee_method',
            field=models.CharField(blank=True, help_text='Payment method used for the assessment fee', max_length=40),
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='assessment_fee_reference',
            field=models.CharField(blank=True, help_text='Payment reference / receipt number', max_length=120),
        ),
    ]
