# Generated by Django 5.2.15 on 2026-08-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_assessmentschedule_assessment_fee_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['created_at'], 'permissions': [('confirm_assessment_fee', 'Can confirm assessment fee payment'), ('reverse_assessment_fee', 'Can reverse assessment fee confirmation'), ('send_assessment_logistics', 'Can send assessment logistics to parent'), ('toggle_admission_document', 'Can toggle document received status'), ('complete_enrolment', 'Can complete student enrolment'), ('schedule_assessment', 'Can schedule an assessment'), ('submit_assessment_result', 'Can submit assessment result'), ('submit_hod_review', 'Can submit HOD review'), ('edit_admission_note', 'Can edit internal admission notes'), ('delete_admission_note', 'Can delete internal admission notes'), ('upload_applicant_photo', 'Can upload applicant photo'), ('transition_applicant_status', 'Can transition applicant status'), ('view_assessment_calendar', 'Can view assessment calendar')]},
        ),
    ]
