# Generated by Django 5.2.15 on 2026-08-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_alter_applicant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('meeting_completed', 'Meeting completed'), ('declined_at_meeting', 'Declined at meeting'), ('report_pending', 'Report pending'), ('assessment_failed', 'Assessment failed'), ('form_submitted', 'Admission form submitted'), ('invoice_generated', 'Invoice generated'), ('invoice_paid', 'Invoice paid'), ('flagged_for_review', 'Flagged for review')], db_index=True, default='inquiry_received', max_length=40),
        ),
        migrations.AlterField(
            model_name='applicanttimelineentry',
            name='from_status',
            field=models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('meeting_completed', 'Meeting completed'), ('declined_at_meeting', 'Declined at meeting'), ('report_pending', 'Report pending'), ('assessment_failed', 'Assessment failed'), ('form_submitted', 'Admission form submitted'), ('invoice_generated', 'Invoice generated'), ('invoice_paid', 'Invoice paid'), ('flagged_for_review', 'Flagged for review')], max_length=40),
        ),
        migrations.AlterField(
            model_name='applicanttimelineentry',
            name='to_status',
            field=models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('meeting_completed', 'Meeting completed'), ('declined_at_meeting', 'Declined at meeting'), ('report_pending', 'Report pending'), ('assessment_failed', 'Assessment failed'), ('form_submitted', 'Admission form submitted'), ('invoice_generated', 'Invoice generated'), ('invoice_paid', 'Invoice paid'), ('flagged_for_review', 'Flagged for review')], max_length=40),
        ),
    ]
