# Generated by Django 5.2.15 on 2026-08-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_add_spec_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('location', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='admissions.applicant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
