# Generated by Django 5.2.15 on 2026-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_add_meetingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingschedule',
            name='location',
            field=models.CharField(default='Hodari Christian School', max_length=120),
        ),
    ]
