# Generated by Django 5.2.15 on 2026-08-22 05:49
# Rewritten to handle orphaned index catalog inconsistency on VPS

from django.db import migrations, models


def add_reference_number_columns(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'sqlite':
        schema_editor.execute("ALTER TABLE admissions_applicant ADD COLUMN reference_number varchar(20) NOT NULL DEFAULT '';")
        schema_editor.execute("CREATE INDEX IF NOT EXISTS admissions_applicant_reference_number_cec30435 ON admissions_applicant (reference_number);")
        return

    schema_editor.execute("DROP INDEX IF EXISTS admissions_applicant_reference_number_cec30435_like;")
    schema_editor.execute("DROP INDEX IF EXISTS admissions_applicant_reference_number_cec30435;")
    schema_editor.execute("ALTER TABLE admissions_applicant ADD COLUMN IF NOT EXISTS reference_number varchar(20) NOT NULL DEFAULT '';")
    schema_editor.execute("CREATE INDEX IF NOT EXISTS admissions_applicant_reference_number_cec30435 ON admissions_applicant USING btree (reference_number);")


def add_reference_number_unique_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'admissions_applicant'::regclass
                AND conname = 'admissions_applicant_reference_number_uniq'
            ) THEN
                ALTER TABLE admissions_applicant
                ADD CONSTRAINT admissions_applicant_reference_number_uniq UNIQUE (reference_number);
            END IF;
        END
        $$;
        """
    )


def backfill_reference_numbers(apps, schema_editor):
    Applicant = apps.get_model('admissions', 'Applicant')
    for applicant in Applicant.objects.order_by('pk'):
        if not applicant.reference_number:
            applicant.reference_number = f"ADM-{applicant.pk:04d}"
            Applicant.objects.filter(pk=applicant.pk).update(reference_number=applicant.reference_number)


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_meeting_location_default'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle orphaned index gracefully.
        # State tracks the field; database ops use idempotent SQL.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='applicant',
                    name='reference_number',
                    field=models.CharField(blank=True, db_index=True, help_text='Auto-generated reference number, e.g. ADM-0001', max_length=20, default=''),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_reference_number_columns, migrations.RunPython.noop),
            ],
        ),
        # Step 2: Backfill reference numbers for existing rows
        migrations.RunPython(backfill_reference_numbers, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='applicant',
                    name='reference_number',
                    field=models.CharField(blank=True, db_index=True, help_text='Auto-generated reference number, e.g. ADM-0001', max_length=20, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_reference_number_unique_constraint, migrations.RunPython.noop),
            ],
        ),
    ]
