# Generated by Django 5.2.15 on 2026-08-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_rename_hod_review_to_hos_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['created_at'], 'permissions': [('confirm_assessment_fee', 'Can confirm assessment fee payment'), ('reverse_assessment_fee', 'Can reverse assessment fee confirmation'), ('send_assessment_logistics', 'Can send assessment logistics to parent'), ('toggle_admission_document', 'Can toggle document received status'), ('complete_enrolment', 'Can complete student enrolment'), ('schedule_assessment', 'Can schedule an assessment'), ('submit_assessment_result', 'Can submit assessment result'), ('submit_hos_review', 'Can submit HOS review'), ('submit_hod_review', 'Can submit HOD review'), ('edit_admission_note', 'Can edit internal admission notes'), ('delete_admission_note', 'Can delete internal admission notes'), ('upload_applicant_photo', 'Can upload applicant photo'), ('transition_applicant_status', 'Can transition applicant status'), ('view_assessment_calendar', 'Can view assessment calendar')]},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hos_review', 'HOS review'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('meeting_completed', 'Meeting completed'), ('declined_at_meeting', 'Declined at meeting'), ('report_pending', 'Report pending'), ('assessment_failed', 'Assessment failed'), ('form_submitted', 'Admission form submitted'), ('invoice_generated', 'Invoice generated'), ('invoice_paid', 'Invoice paid'), ('flagged_for_review', 'Flagged for review')], db_index=True, default='inquiry_received', max_length=40),
        ),
        migrations.AlterField(
            model_name='applicanttimelineentry',
            name='from_status',
            field=models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hos_review', 'HOS review'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('meeting_completed', 'Meeting completed'), ('declined_at_meeting', 'Declined at meeting'), ('report_pending', 'Report pending'), ('assessment_failed', 'Assessment failed'), ('form_submitted', 'Admission form submitted'), ('invoice_generated', 'Invoice generated'), ('invoice_paid', 'Invoice paid'), ('flagged_for_review', 'Flagged for review')], max_length=40),
        ),
        migrations.AlterField(
            model_name='applicanttimelineentry',
            name='to_status',
            field=models.CharField(choices=[('inquiry_received', 'Inquiry received'), ('meeting_scheduled', 'Meeting scheduled'), ('assessment_pending', 'Assessment pending'), ('assessment_fee_paid', 'Assessment fee paid'), ('assessment_confirmed', 'Assessment confirmed'), ('assessment_completed', 'Assessment completed'), ('hos_review', 'HOS review'), ('hod_review', 'HOD review'), ('hos_decision', 'HOS decision'), ('admitted', 'Admitted'), ('conditional', 'Conditional'), ('denied', 'Denied'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('meeting_completed', 'Meeting completed'), ('declined_at_meeting', 'Declined at meeting'), ('report_pending', 'Report pending'), ('assessment_failed', 'Assessment failed'), ('form_submitted', 'Admission form submitted'), ('invoice_generated', 'Invoice generated'), ('invoice_paid', 'Invoice paid'), ('flagged_for_review', 'Flagged for review')], max_length=40),
        ),
        migrations.AlterField(
            model_name='meetingschedule',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
