# Generated by Django 5.2.15 on 2026-08-23 07:42
# Rewritten with SeparateDatabaseAndState for idempotent DB operations

from django.db import migrations, models


def add_parent_facing_comments(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("ALTER TABLE admissions_assessmentschedule ADD COLUMN parent_facing_comments text NOT NULL DEFAULT '';")
        return
    schema_editor.execute("ALTER TABLE admissions_assessmentschedule ADD COLUMN IF NOT EXISTS parent_facing_comments text NOT NULL DEFAULT '';")


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_rename_hod_review_to_hos_review'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='assessmentschedule',
                    name='parent_facing_comments',
                    field=models.TextField(blank=True, help_text='Feedback visible to parents (e.g. in offer letter or denial email)'),
                ),
                migrations.AlterField(
                    model_name='assessmentschedule',
                    name='hod_comments',
                    field=models.TextField(blank=True, help_text='Internal staff comments -- never shown to parents'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_parent_facing_comments, migrations.RunPython.noop),
            ],
        ),
    ]
