# Generated by Django 5.2.15 on 2026-08-23 08:07
# Rewritten with SeparateDatabaseAndState for idempotent DB operations

from django.db import migrations, models


def add_preferred_meeting_fields(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("ALTER TABLE admissions_applicant ADD COLUMN preferred_meeting_date date NULL;")
        schema_editor.execute("ALTER TABLE admissions_applicant ADD COLUMN preferred_meeting_time time NULL;")
        return
    schema_editor.execute("ALTER TABLE admissions_applicant ADD COLUMN IF NOT EXISTS preferred_meeting_date date NULL;")
    schema_editor.execute("ALTER TABLE admissions_applicant ADD COLUMN IF NOT EXISTS preferred_meeting_time time NULL;")


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_add_parent_facing_comments'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='applicant',
                    name='preferred_meeting_date',
                    field=models.DateField(blank=True, help_text="Parent's preferred meeting date from inquiry form", null=True),
                ),
                migrations.AddField(
                    model_name='applicant',
                    name='preferred_meeting_time',
                    field=models.TimeField(blank=True, help_text="Parent's preferred meeting time from inquiry form", null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_preferred_meeting_fields, migrations.RunPython.noop),
            ],
        ),
    ]
