# Generated by Django 5.2.15 on 2026-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0025_add_preferred_meeting_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='parent_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('Father', 'Father'), ('mother', 'Mother'), ('Mother', 'Mother'), ('guardian', 'Guardian'), ('Guardian', 'Guardian'), ('legal_guardian', 'Legal guardian'), ('Legal guardian', 'Legal guardian'), ('legal guardian', 'Legal guardian'), ('other', 'Other'), ('Other', 'Other')], default='', help_text='Relationship of parent/guardian to the student.', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessmentschedule',
            name='hod_comments',
            field=models.TextField(blank=True, help_text='Internal staff comments — never shown to parents'),
        ),
    ]
