# Generated by Django 5.2.15 on 2026-09-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0026_alter_applicant_parent_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='target_enrollment_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month (1-12) the parent intends to enroll the child, e.g. 8 for August', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='target_enrollment_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the parent intends to enroll the child, e.g. 2027', null=True),
        ),
    ]
