# Generated by Django 5.2.17 on 2026-09-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0027_add_target_enrollment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='parent_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('Father', 'Father'), ('mother', 'Mother'), ('Mother', 'Mother'), ('guardian', 'Guardian'), ('Guardian', 'Guardian'), ('legal_guardian', 'Legal guardian'), ('Legal guardian', 'Legal guardian'), ('legal guardian', 'Legal guardian'), ('other', 'Other'), ('Other', 'Other')], default='', max_length=30),
        ),
    ]
