# Generated by Django 5.2.17 on 2026-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0028_alter_applicant_parent_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['created_at'], 'permissions': [('confirm_assessment_fee', 'Can confirm assessment fee payment'), ('reverse_assessment_fee', 'Can reverse assessment fee confirmation'), ('send_assessment_logistics', 'Can send assessment logistics to parent'), ('toggle_admission_document', 'Can toggle document received status'), ('complete_enrolment', 'Can complete student enrolment'), ('schedule_assessment', 'Can schedule an assessment'), ('submit_assessment_result', 'Can submit assessment result'), ('submit_hos_review', 'Can submit HOS review'), ('submit_hod_review', 'Can submit HOD review'), ('edit_admission_note', 'Can edit internal admission notes'), ('delete_admission_note', 'Can delete internal admission notes'), ('upload_applicant_photo', 'Can upload applicant photo'), ('transition_applicant_status', 'Can transition applicant status'), ('view_assessment_calendar', 'Can view assessment calendar'), ('direct_enrol', 'Can enrol a learner directly, skipping assessment')]},
        ),
        migrations.AddField(
            model_name='applicant',
            name='direct_enrolment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='direct_enrolment_reason',
            field=models.CharField(blank=True, choices=[('transfer', 'Transfer from another school'), ('mid_year', 'Mid-year entry'), ('staff_child', 'Staff child'), ('returning', 'Returning learner')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='entry_route',
            field=models.CharField(choices=[('pipeline', 'Admissions pipeline'), ('direct', 'Direct enrolment')], db_index=True, default='pipeline', max_length=20),
        ),
    ]
