# Generated by Django 5.2.17 on 2026-09-27 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0029_direct_enrolment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='child_date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='entry_route',
            field=models.CharField(choices=[('pipeline', 'Admissions pipeline'), ('direct', 'Direct enrolment'), ('parent_link', 'Parent completed form via link')], db_index=True, default='pipeline', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantdocumentreceipt',
            name='document_type',
            field=models.CharField(choices=[('birth_certificate', 'Birth certificate'), ('clearance_form', 'Clearance form (previous school)'), ('admission_form', 'Completed admission form'), ('fee_arrangement_proof', 'Proof of fee payment arrangement'), ('previous_report', 'Previous school report'), ('student_photo', 'Passport photo of the learner'), ('passport_permit', 'Passport or residence permit'), ('parent_id', 'Parent national ID')], max_length=40),
        ),
        migrations.CreateModel(
            name='AdmissionFormInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Form sent'), ('in_progress', 'Parent filling in'), ('submitted', 'Submitted by parent'), ('changes_requested', 'Changes requested'), ('accepted', 'Accepted')], db_index=True, default='sent', max_length=20)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_message', models.TextField(blank=True, help_text='What the parent was asked to fix or add.')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_invite', to='admissions.applicant')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
