# Generated by Django 5.2.18 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0031_remove_direct_enrol_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='direct_enrolment_reason',
            field=models.CharField(blank=True, choices=[('transfer', 'Transfer from another school'), ('mid_year', 'Mid-year entry'), ('staff_child', 'Staff child'), ('returning', 'Returning student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantdocumentreceipt',
            name='document_type',
            field=models.CharField(choices=[('birth_certificate', 'Birth certificate'), ('clearance_form', 'Clearance form (previous school)'), ('admission_form', 'Completed admission form'), ('fee_arrangement_proof', 'Proof of fee payment arrangement'), ('previous_report', 'Previous school report'), ('student_photo', 'Passport photo of the student'), ('passport_permit', 'Passport or residence permit'), ('parent_id', 'Parent national ID')], max_length=40),
        ),
    ]
