# Generated by Django 5.2.15 on 2026-06-21 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_initial'),
        ('students', '0007_student_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplineincident',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='hod_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discipline_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending_review', max_length=30),
        ),
        migrations.AddIndex(
            model_name='disciplineincident',
            index=models.Index(fields=['student', 'status'], name='discipline__student_7000b5_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineincident',
            index=models.Index(fields=['severity', 'status'], name='discipline__severit_5b185a_idx'),
        ),
    ]
