# Generated by Django 5.2.15 on 2026-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_alter_disciplineincident_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineincident',
            name='actions_taken_detailed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='incident_level_1',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='incident_level_2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='incident_level_3',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='incident_level_4',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='previous_incidents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='time_of_incident',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
