# Generated by Django 5.2.15 on 2026-06-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0004_add_detailed_discipline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineincident',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='incident_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='parent_contact_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='parent_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
