# Generated by Django 5.2.15 on 2026-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0006_add_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disciplineincident',
            name='idx_di_reported_by',
        ),
        migrations.RemoveIndex(
            model_name='disciplineincident',
            name='idx_di_severity',
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='parent_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='parent_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
