# Generated by Django 5.2.15 on 2026-08-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0007_add_parent_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplineincident',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_incident', 'Can review and approve discipline incidents')]},
        ),
    ]
