# Generated by Django 5.2.18 on 2026-10-08 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def carry_over(apps, schema_editor):
    """Keep the contact date from the old date-and-time field; mark existing
    follow-ups as a general follow-up, since their kind was never recorded."""
    Incident = apps.get_model("discipline", "DisciplineIncident")
    for incident in Incident.objects.exclude(parent_contact_datetime=None):
        when = incident.parent_contact_datetime
        if timezone.is_aware(when):
            when = timezone.localtime(when)
        incident.parent_contact_date = when.date()
        incident.save(update_fields=["parent_contact_date"])
    Incident.objects.filter(follow_up_required=True).update(follow_up_kind="other")


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0008_alter_disciplineincident_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineincident',
            name='follow_up_kind',
            field=models.CharField(blank=True, choices=[('meeting', 'Meeting arranged'), ('call', 'Call arranged'), ('other', 'Follow-up arranged')], max_length=20),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='parent_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='parent_contact_method',
            field=models.CharField(blank=True, choices=[('telephone', 'By telephone'), ('in_person', 'In person'), ('message', 'By message'), ('email', 'By email'), ('letter', 'By letter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disciplineincident',
            name='severity',
            field=models.CharField(choices=[('low', 'Level 1 — Minor'), ('medium', 'Level 2 — Moderate'), ('high', 'Level 3 — Serious'), ('critical', 'Level 4 — Severe')], max_length=20),
        ),
        migrations.RunPython(carry_over, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='disciplineincident',
            name='parent_contact_datetime',
        ),
        migrations.RemoveField(
            model_name='disciplineincident',
            name='previous_incidents',
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='follow_up_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='parent_contact_person',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='IncidentAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('changes', models.JSONField(default=list)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='discipline.disciplineincident')),
            ],
            options={
                'ordering': ['changed_at', 'pk'],
            },
        ),
    ]
