# Generated by Django 5.2.16 on 2026-07-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_actor_db_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSARRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('student', 'Student'), ('guardian', 'Guardian')], max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('target_label', models.CharField(help_text='Human-readable label for the data subject (e.g. name).', max_length=200)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'XLSX')], default='json', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired (timeout)')], db_index=True, default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Elapsed time in seconds from start to completion.', null=True)),
                ('modules_included', models.JSONField(blank=True, default=list, help_text='List of data modules included in the export.')),
                ('modules_expected', models.JSONField(blank=True, default=list, help_text='Full list of modules that should be in a complete DSAR export.')),
                ('within_sla', models.BooleanField(blank=True, help_text='True if export completed within 30 minutes.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the export failed.')),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DSAR Request',
                'verbose_name_plural': 'DSAR Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
