# Generated by Django 5.2.18 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_dsarrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsarrequest',
            name='target_type',
            field=models.CharField(choices=[('student', 'Student'), ('guardian', 'Parent')], max_length=16),
        ),
    ]
