# Generated by Django 5.2.15 on 2026-08-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_make_due_date_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'due_date', '-created_at'], 'permissions': [('view_department_tasks', 'Can view tasks across the whole department (department managers)')], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
