# Generated by Django 5.2.15 on 2026-08-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('admission_review', 'Admission Review'), ('assessment_scheduling', 'Assessment Scheduling'), ('enrolment_processing', 'Enrolment Processing'), ('applicant_followup', 'Applicant Follow-up'), ('lesson_plan_review', 'Lesson Plan Review'), ('lesson_plan_revision', 'Lesson Plan Revision'), ('lesson_plan_submission', 'Lesson Plan Submission'), ('grade_approval', 'Grade Approval'), ('grade_submission', 'Grade Submission'), ('report_signoff', 'Report Sign-Off'), ('report_comment', 'Report Comment Submission'), ('at_risk_alert', 'At-Risk Student Alert'), ('assessment_entry', 'Assessment Data Entry'), ('assessment_report', 'Assessment Report Submission'), ('ecd_report_submission', 'ECD Report Submission'), ('welfare_alert', 'Welfare Alert'), ('welfare_followup', 'Welfare Follow-Up'), ('ecd_attendance', 'ECD Attendance Issue'), ('weekly_focus_submission', 'Weekly Focus Submission'), ('compliance_check', 'Compliance Check'), ('department_review', 'Department Review'), ('attendance_alert', 'Attendance Alert'), ('lesson_plan_compliance', 'Lesson Plan Compliance'), ('payment_matching', 'Payment Matching'), ('overdue_collection', 'Overdue Collection'), ('fee_verification', 'Fee Verification'), ('sibling_discount', 'Sibling Discount Verification'), ('assessment_fee', 'Assessment Fee Tracking'), ('event_rsvp', 'Event RSVP'), ('event_creation', 'Event Creation'), ('fee_payment_reminder', 'Fee Payment Reminder'), ('document_upload', 'Document Upload'), ('attendance_confirmation', 'Attendance Confirmation'), ('general_task', 'General Task'), ('discipline_contact', 'Discipline Parent Contact'), ('report_card_ready', 'Report Card Available'), ('open_invoice', 'Open Invoice Reminder')], help_text='Category of task', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_type',
            field=models.CharField(choices=[('admission_review', 'Admission Review'), ('assessment_scheduling', 'Assessment Scheduling'), ('enrolment_processing', 'Enrolment Processing'), ('applicant_followup', 'Applicant Follow-up'), ('lesson_plan_review', 'Lesson Plan Review'), ('lesson_plan_revision', 'Lesson Plan Revision'), ('lesson_plan_submission', 'Lesson Plan Submission'), ('grade_approval', 'Grade Approval'), ('grade_submission', 'Grade Submission'), ('report_signoff', 'Report Sign-Off'), ('report_comment', 'Report Comment Submission'), ('at_risk_alert', 'At-Risk Student Alert'), ('assessment_entry', 'Assessment Data Entry'), ('assessment_report', 'Assessment Report Submission'), ('ecd_report_submission', 'ECD Report Submission'), ('welfare_alert', 'Welfare Alert'), ('welfare_followup', 'Welfare Follow-Up'), ('ecd_attendance', 'ECD Attendance Issue'), ('weekly_focus_submission', 'Weekly Focus Submission'), ('compliance_check', 'Compliance Check'), ('department_review', 'Department Review'), ('attendance_alert', 'Attendance Alert'), ('lesson_plan_compliance', 'Lesson Plan Compliance'), ('payment_matching', 'Payment Matching'), ('overdue_collection', 'Overdue Collection'), ('fee_verification', 'Fee Verification'), ('sibling_discount', 'Sibling Discount Verification'), ('assessment_fee', 'Assessment Fee Tracking'), ('event_rsvp', 'Event RSVP'), ('event_creation', 'Event Creation'), ('fee_payment_reminder', 'Fee Payment Reminder'), ('document_upload', 'Document Upload'), ('attendance_confirmation', 'Attendance Confirmation'), ('general_task', 'General Task'), ('discipline_contact', 'Discipline Parent Contact'), ('report_card_ready', 'Report Card Available'), ('open_invoice', 'Open Invoice Reminder')], max_length=50),
        ),
    ]
