# Generated by Django 5.2.15 on 2026-06-17 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0014_alter_abcgeneralassignment_quarter_and_more'),
        ('students', '0006_laravelparent_studentlaravelparent_student_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Bible', 'Bible'), ('ICT', 'ICT'), ('Global Perspective', 'Global Perspective'), ('PE', 'PE'), ('Swimming', 'Swimming'), ('French', 'French'), ('Music', 'Music')], max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_class', models.ForeignKey(blank=True, help_text='Class this enrichment subject is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_subjects', to='academics.gradeclass')),
                ('assigned_teacher', models.ForeignKey(blank=True, help_text='Specialist teacher assigned to this enrichment subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrichment Subject',
                'verbose_name_plural': 'Enrichment Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PTCWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_slot', models.CharField(choices=[('term_1', 'Term 1'), ('term_3', 'Term 3')], help_text='Term 1 or Term 3', max_length=10)),
                ('ptc_date', models.DateField(help_text='The date the parent-teacher conference is held')),
                ('notification_window_days', models.PositiveIntegerField(default=30, help_text='Days before PTC date when the notification window opens. Configurable by Super Admin.')),
                ('notification_window_opens_at', models.DateField(blank=True, editable=False, help_text='Computed: ptc_date - notification_window_days', null=True)),
                ('notification_window_closes_at', models.DateField(blank=True, editable=False, help_text='Computed: ptc_date - 4 days (hardcoded per FR-PTC-003)', null=True)),
                ('comment_entry_window_days', models.PositiveIntegerField(default=14, help_text='Days before PTC date when the comment/attribute entry window opens. Fixed by FRD but stored for flexibility.')),
                ('comment_entry_window_opens_at', models.DateField(blank=True, editable=False, help_text='Computed: ptc_date - comment_entry_window_days', null=True)),
                ('comment_entry_window_closes_at', models.DateField(blank=True, editable=False, help_text='Computed: ptc_date (window closes on PTC date itself)', null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Once published, date changes require Super Admin and are audited (FR-PTC-002).')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_windows', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ptc_windows_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ptc_windows_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['academic_year__name', 'term_slot'],
                'unique_together': {('academic_year', 'term_slot')},
            },
        ),
        migrations.CreateModel(
            name='PTCDateChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_ptc_date', models.DateField()),
                ('new_ptc_date', models.DateField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_date_changes', to=settings.AUTH_USER_MODEL)),
                ('ptc_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_change_logs', to='ptc.ptcwindow')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_grade', models.CharField(blank=True, choices=[('A*', 'Outstanding (90-100)'), ('A', 'High (80-89)'), ('B', 'Good (70-79)'), ('C', 'Aspiring (60-69)'), ('D', 'Basic (50-59)'), ('E', 'Needs Improvement (0-49)')], default='', max_length=2)),
                ('is_locked', models.BooleanField(default=False)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_grades_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_grades', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_grades', to='academics.term')),
                ('enrichment_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='ptc.enrichmentsubject')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'term'], name='ptc_enrichm_student_6abe78_idx'), models.Index(fields=['enrichment_subject', 'term'], name='ptc_enrichm_enrichm_590730_idx')],
                'unique_together': {('student', 'enrichment_subject', 'term')},
            },
        ),
        migrations.CreateModel(
            name='PTCSubjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(db_index=True, help_text='Core subject name matching the grade entry system', max_length=80)),
                ('comment_text', models.TextField(blank=True, default='', help_text='Free text. Soft hint: recommended 30 chars. No hard minimum (FR-PTC-012).')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ptc_comments_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_comments', to='students.student')),
                ('ptc_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_comments', to='ptc.ptcwindow')),
            ],
            options={
                'indexes': [models.Index(fields=['ptc_window', 'subject_name'], name='ptc_ptcsubj_ptc_win_ec70ab_idx'), models.Index(fields=['student', 'ptc_window'], name='ptc_ptcsubj_student_40b0a7_idx')],
                'unique_together': {('student', 'ptc_window', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='PTCGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_generation_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_generation_logs', to='students.student')),
                ('ptc_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='ptc.ptcwindow')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['student', 'opened_at'], name='ptc_ptcgene_student_9b5819_idx'), models.Index(fields=['class_teacher', 'opened_at'], name='ptc_ptcgene_class_t_ff3219_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearnerAttributeRatingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_number', models.PositiveSmallIntegerField(choices=[('1', 'Writes with good and neat handwriting at a desirable speed'), ('2', 'Works well independently'), ('3', 'Works well in a group setting'), ('4', 'Is able to manage time well'), ('5', 'Readiness to listen and pay attention to lessons'), ('6', 'Completes homework and assignments'), ('7', 'Reads grade content to standard'), ('8', 'Comprehends grade level content'), ('9', 'Respects authority and has a good attitude towards discipline'), ('10', 'Attention to personal hygiene and appearance'), ('11', 'Relates well with others'), ('12', 'Attendance and timely arrival to school')], help_text='1-12 matching the fixed attribute list (FR-PTC-019)')),
                ('rating', models.CharField(blank=True, choices=[('E', 'Excellent'), ('G', 'Good'), ('S', 'Satisfactory'), ('N', 'Needs Improvement')], default='', help_text='E/G/S/N', max_length=1)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ptc_attribute_ratings_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_attribute_ratings', to='students.student')),
                ('ptc_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_ratings', to='ptc.ptcwindow')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name', 'attribute_number'],
                'indexes': [models.Index(fields=['ptc_window', 'student'], name='ptc_learner_ptc_win_e4abd5_idx'), models.Index(fields=['student', 'ptc_window'], name='ptc_learner_student_44d64e_idx')],
                'unique_together': {('student', 'ptc_window', 'attribute_number')},
            },
        ),
    ]
