# Generated by Django 5.2.15 on 2026-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerattributeratingentry',
            name='attribute_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Writes with good and neat handwriting at a desirable speed'), (2, 'Works well independently'), (3, 'Works well in a group setting'), (4, 'Is able to manage time well'), (5, 'Readiness to listen and pay attention to lessons'), (6, 'Completes homework and assignments'), (7, 'Reads grade content to standard'), (8, 'Comprehends grade level content'), (9, 'Respects authority and has a good attitude towards discipline'), (10, 'Attention to personal hygiene and appearance'), (11, 'Relates well with others'), (12, 'Attendance and timely arrival to school')], help_text='1-12 matching the fixed attribute list (FR-PTC-019)'),
        ),
    ]
