# Generated by Django 5.2.15 on 2026-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0002_alter_learnerattributeratingentry_attribute_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerattributeratingentry',
            name='attribute_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Writes with good and neat handwriting at a desirable speed'), (2, 'Reads grade content to standard'), (3, 'Works well independently'), (4, 'Comprehends grade level content'), (5, 'Works well in a group setting'), (6, 'Respects authority and has a good attitude towards discipline'), (7, 'Is able to manage time well'), (8, 'Attention to personal hygiene and appearance'), (9, 'Readiness to listen and pay attention to lessons'), (10, 'Relates well with others'), (11, 'Completes homework and assignments'), (12, 'Attendance and timely arrival to school')], help_text='1-12 matching the fixed attribute list (FR-PTC-019)'),
        ),
        migrations.AlterField(
            model_name='ptcwindow',
            name='term_slot',
            field=models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], help_text='Term 1 or Term 3', max_length=10),
        ),
    ]
