# Generated by Django 5.2.15 on 2026-06-20 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0003_alter_learnerattributeratingentry_attribute_number_and_more'),
        ('students', '0007_student_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentgrade',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A*', 'Outstanding (90 - 100)'), ('A', 'High (80 - 89)'), ('B', 'Good (70 - 79)'), ('C', 'Aspiring (60 - 69)'), ('D', 'Basic (50 - 59)'), ('E', 'Needs Improvement (49 - 0)')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='enrichmentsubject',
            name='name',
            field=models.CharField(choices=[('Bible', 'Bible'), ('PE', 'PE'), ('French', 'French'), ('ICT', 'ICT'), ('Swimming', 'Swimming'), ('Music', 'Music'), ('Global Perspective', 'Global Perspective')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptcwindow',
            name='term_slot',
            field=models.CharField(choices=[('term_1', 'Term 1'), ('term_3', 'Term 3')], help_text='Term 1 or Term 3 (FR-PTC-001)', max_length=10),
        ),
        migrations.CreateModel(
            name='PTCProgressTrendOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overridden_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('needs_attention', 'Needs Attention')], help_text='Teacher-selected trend override', max_length=20)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_trend_overrides_entered', to=settings.AUTH_USER_MODEL)),
                ('ptc_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trend_overrides', to='ptc.ptcwindow')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptc_trend_overrides', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'ptc_window')},
            },
        ),
    ]
