# Generated by Django 5.2.15 on 2026-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0004_alter_enrichmentgrade_letter_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentsubject',
            name='name',
            field=models.CharField(choices=[('Bible', 'Bible'), ('ICT', 'ICT'), ('Global Perspective', 'Global Perspective'), ('PE', 'PE'), ('Swimming', 'Swimming'), ('French', 'French'), ('Music', 'Music')], max_length=40, unique=True),
        ),
    ]
