# Generated by Django 5.2.15 on 2026-08-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0005_alter_enrichmentsubject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrichmentsubject',
            options={'ordering': ['name'], 'permissions': [('manage_enrichment_config', 'Can manage enrichment subject configuration')], 'verbose_name': 'Enrichment Subject', 'verbose_name_plural': 'Enrichment Subjects'},
        ),
        migrations.AddField(
            model_name='enrichmentsubject',
            name='weight_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight percentage for report card calculation (0 = letter grade only, no weighted avg)', max_digits=5),
        ),
    ]
