# Generated by Django 5.2.15 on 2026-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0006_add_enrichment_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentsubject',
            name='name',
            field=models.CharField(help_text='Name of the enrichment subject (e.g. Bible, ICT, Music)', max_length=40, unique=True),
        ),
    ]
