# Generated by Django 5.2.13 on 2026-04-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(db_index=True, max_length=64)),
                ('stream_name', models.CharField(blank=True, max_length=64)),
                ('subject_name', models.CharField(max_length=80)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], db_index=True, max_length=8)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=80)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['class_name', 'day_of_week', 'start_time'], name='timetable_t_class_n_c3fe23_idx'), models.Index(fields=['teacher', 'day_of_week', 'start_time'], name='timetable_t_teacher_c2e4a0_idx')],
            },
        ),
    ]
