# Generated by Django 4.2.30 on 2026-05-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_examscore_approved_at_examscore_approved_by_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timetableslot',
            name='timetable_t_class_n_c3fe23_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetableslot',
            name='timetable_t_teacher_c2e4a0_idx',
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='academics.term'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['term', 'class_name', 'day_of_week', 'start_time'], name='timetable_t_term_id_0630ed_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['term', 'teacher', 'day_of_week', 'start_time'], name='timetable_t_term_id_895d94_idx'),
        ),
    ]
