# Generated by Django 5.2.14 on 2026-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_timetableslot_timetable_t_class_n_c3fe23_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcdBreakConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=64, unique=True)),
                ('snack_break_start', models.TimeField()),
                ('snack_break_end', models.TimeField()),
                ('lunch_break_start', models.TimeField()),
                ('lunch_break_end', models.TimeField()),
                ('nap_time_start', models.TimeField(blank=True, null=True)),
                ('nap_time_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
