# Generated by Django 5.2.14 on 2026-05-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_room'),
        ('timetable', '0003_ecdbreakconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='location',
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='academics.room'),
        ),
    ]
