# Generated by Django 5.2.14 on 2026-05-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_timetableslot_location_timetableslot_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='stream_name',
        ),
    ]
