# Generated by Django 5.2.14 on 2026-05-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_subject_code_subject_color'),
        ('timetable', '0005_remove_timetableslot_stream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='academics.subject'),
        ),
    ]
