# Generated by Django 5.2.15 on 2026-07-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0038_backfill_endterm_exam_dates'),
        ('timetable', '0007_add_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timetableslot',
            name='idx_tt_teacher',
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='academics.subject'),
        ),
    ]
