# Generated by Django 5.2.15 on 2026-07-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_timetableslot_idx_tt_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
