# Generated by Django 5.2.15 on 2026-07-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_add_is_published'),
        ('timetable', '0009_alter_timetableslot_subject'),
    ]

    operations = [
    ]
