# Generated by Django 5.2.15 on 2026-08-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_timetableslot_idx_tt_teacher'),
        ('timetable', '0010_merge_20260714_2114'),
    ]

    operations = [
    ]
