# Generated by Django 5.2.13 on 2026-04-23 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(db_index=True, max_length=64)),
                ('subject_name', models.CharField(db_index=True, max_length=80)),
                ('week_start_date', models.DateField(db_index=True)),
                ('lesson_title', models.CharField(max_length=150)),
                ('objectives', models.TextField()),
                ('activities', models.TextField()),
                ('assessment_strategy', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plan_reviews', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academics.term')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'week_start_date'], name='academics_l_status_6cf937_idx'), models.Index(fields=['teacher', 'status'], name='academics_l_teacher_4d95fd_idx')],
            },
        ),
    ]
