# Generated by Django 4.2.27 on 2026-05-01 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_parentguardian_archived_at_and_more'),
        ('academics', '0002_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_sign_off', 'Pending HOS sign-off'), ('published', 'Published to parents')], db_index=True, default='draft', max_length=20)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_comments', models.TextField(blank=True)),
                ('hos_comments', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_signed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academics.term')),
            ],
            options={
                'ordering': ['-term__academic_year__name', 'term__name', 'student__last_name'],
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(db_index=True, max_length=80)),
                ('exam_type', models.CharField(choices=[('quiz', 'Quiz (20%)'), ('mid_term', 'Mid-term (30%)'), ('end_of_term', 'End of Term (50%)')], db_index=True, max_length=15)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('correction_reason', models.TextField(blank=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scores_corrected', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_scores', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_scores', to='academics.term')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'term'], name='academics_e_student_30f2b0_idx'), models.Index(fields=['term', 'subject_name'], name='academics_e_term_id_184d51_idx')],
                'unique_together': {('student', 'term', 'subject_name', 'exam_type')},
            },
        ),
    ]
