# Generated by Django 5.2.13 on 2026-05-04 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_term_end_date_term_start_date_reportcard_examscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(choices=[('ECD', 'ECD'), ('PRIMARY', 'Primary'), ('LOWER_SECONDARY', 'Lower Secondary'), ('ADMINISTRATION', 'Administration')], max_length=32)),
                ('max_capacity', models.PositiveIntegerField(default=25)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('department', models.CharField(choices=[('ECD', 'ECD'), ('PRIMARY', 'Primary'), ('LOWER_SECONDARY', 'Lower Secondary'), ('ADMINISTRATION', 'Administration')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reportcard',
            name='ecd_template_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='is_ecd_report',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ECDEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('S', 'Satisfactory'), ('N', 'Needs Improvement')], max_length=2)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecd_evaluations', to='academics.reportcard')),
            ],
            options={
                'unique_together': {('report_card', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(db_index=True, max_length=64)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=40)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'unique_together': {('class_name', 'day_of_week', 'start_time')},
            },
        ),
    ]
