# Generated by Django 4.2.30 on 2026-05-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_gradeclass_subject_reportcard_ecd_template_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scores_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examscore',
            name='hod_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to HOD'), ('approved', 'HOD Approved'), ('returned', 'Returned for Correction')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CambridgeCheckpointScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(max_length=80)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpoint_scores', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'academic_year', 'subject_name')},
            },
        ),
    ]
