# Generated by Django 5.2.14 on 2026-05-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_exam_type_configuration'),
        ('academics', '0006_room'),
    ]

    operations = [
    ]
