# Generated by Django 5.2.14 on 2026-05-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_term_grading_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecdtemplateconfiguration',
            name='code',
            field=models.CharField(help_text='Unique code for internal use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='exam_type',
            field=models.CharField(db_index=True, help_text='Exam type code from ExamTypeConfiguration', max_length=20),
        ),
        migrations.CreateModel(
            name='ABCGeneralAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')])),
                ('item_name', models.CharField(max_length=150)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_assignments', to='academics.reportcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ABCPaceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=64)),
                ('pace_no', models.CharField(max_length=10)),
                ('sticker_no', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('in_progress', 'In progress')], max_length=20)),
                ('supervisor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moderator_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_completed', models.CharField(blank=True, max_length=40)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_pace_progress', to='academics.reportcard')),
            ],
            options={
                'verbose_name': 'ABC PACE Progress',
                'verbose_name_plural': 'ABC PACE Progress',
            },
        ),
        migrations.CreateModel(
            name='ABCReadingProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')])),
                ('wpm', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comprehension_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_reading', to='academics.reportcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ABCScripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')])),
                ('verse', models.CharField(max_length=255)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_scripture', to='academics.reportcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonPlanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='lesson_plans/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='academics.lessonplan')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
