# Generated by Django 5.2.14 on 2026-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_ecdtemplateconfiguration_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='e.g. MATH, ENG', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#023AA5', help_text='Hex color for timetable display', max_length=20),
        ),
    ]
