# Generated by Django 5.2.14 on 2026-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_subject_code_subject_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.gradeclass'),
        ),
    ]
