# Generated by Django 5.2.15 on 2026-06-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subject_classes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_days_absent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_days_late',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_days_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Attendance rate as percentage for the term', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term this timetable belongs to — FR-TT-002', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.term'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('term', 'class_name', 'day_of_week', 'start_time')},
        ),
    ]
