# Generated by Django 5.2.15 on 2026-06-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_make_lesson_plan_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcgeneralassignment',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3'), (4, 'Term 4')]),
        ),
        migrations.AlterField(
            model_name='abcreadingprogramme',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3'), (4, 'Term 4')]),
        ),
        migrations.AlterField(
            model_name='abcscripture',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3'), (4, 'Term 4')]),
        ),
    ]
