# Generated by Django 5.2.15 on 2026-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_abcgeneralassignment_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeclass',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Numeric order for grade progression/promotion'),
        ),
    ]
