# Generated by Django 5.2.15 on 2026-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_gradeclass_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='number_of_terms',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of terms in this academic year (e.g. 3 or 4).'),
        ),
    ]
