# Generated by Django 5.2.15 on 2026-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_add_number_of_terms_to_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcgeneralassignment',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='abcreadingprogramme',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='abcscripture',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
    ]
