# Generated by Django 5.2.15 on 2026-06-24 14:36

import academics.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_abcgeneralassignment_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplanattachment',
            name='file',
            field=models.FileField(upload_to='lesson_plans/attachments/', validators=[academics.validators.validate_attachment_file]),
        ),
    ]
