# Generated by Django 5.2.15 on 2026-06-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_lessonplanattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='exam_end_date',
            field=models.DateField(blank=True, help_text='End of end-of-term examination period.', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='exam_start_date',
            field=models.DateField(blank=True, help_text='Start of end-of-term examination period.', null=True),
        ),
    ]
