# Generated by Django 5.2.15 on 2026-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_term_exam_end_date_term_exam_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='comments_submitted',
            field=models.BooleanField(default=False, help_text='Teacher has submitted comments for HOD/HOS review'),
        ),
    ]
