# Generated by Django 5.2.15 on 2026-06-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_reportcard_ecd_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCInternalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=64)),
                ('rating', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('S', 'Satisfactory'), ('N', 'Needs Improvement')], max_length=2)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_internal_exams', to='academics.reportcard')),
            ],
            options={
                'verbose_name': 'ABC Internal Exam',
                'verbose_name_plural': 'ABC Internal Exams',
                'unique_together': {('report_card', 'subject')},
            },
        ),
    ]
