# Generated by Django 5.2.15 on 2026-06-27 08:32

import academics.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_abc_internal_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplanattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to='lesson_plans/attachments/', validators=[academics.validators.validate_attachment_file]),
        ),
    ]
