# Generated by Django 5.2.15 on 2026-06-29 08:51

from django.db import migrations, models


def copy_department_to_departments(apps, schema_editor):
    Subject = apps.get_model("academics", "Subject")
    for s in Subject.objects.iterator():
        if s.department:
            s.departments = [s.department]
            s.save(update_fields=["departments"])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_increase_lessonplanattachment_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='departments',
            field=models.JSONField(blank=True, default=list, help_text='List of departments this subject belongs to'),
        ),
        migrations.RunPython(copy_department_to_departments, migrations.RunPython.noop),
    ]
