# Generated by Django 5.2.15 on 2026-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_subject_departments_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('missing', 'Missing')], db_index=True, default='draft', max_length=30),
        ),
    ]
