# Generated by Django 5.2.15 on 2026-07-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_add_abc_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_average', models.FloatField(default=0.0, help_text='Minimum overall average score required for promotion (0-100).')),
                ('min_attendance', models.FloatField(default=0.0, help_text='Minimum attendance rate percentage required for promotion (0-100).')),
                ('is_committed', models.BooleanField(default=False, help_text='True if changes were applied (not dry-run).')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('repeated_count', models.PositiveIntegerField(default=0)),
                ('graduated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('results_json', models.JSONField(blank=True, default=list, help_text='Per-student detail: [{student_id, name, admission_no, old_class, new_class, action, meets_avg, meets_att, avg, att_rate}]')),
                ('academic_year_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_runs_from', to='academics.academicyear')),
                ('academic_year_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_runs_to', to='academics.academicyear')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Run',
                'verbose_name_plural': 'Promotion Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
