# Generated by Django 5.2.15 on 2026-07-03 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_add_promotion_run'),
        ('students', '0009_enrollment_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_average', models.FloatField(default=50.0, help_text='Minimum overall average required for promotion (0-100).')),
                ('minimum_attendance', models.FloatField(default=80.0, help_text='Minimum attendance rate percentage required for promotion (0-100).')),
                ('retention_threshold', models.FloatField(default=50.0, help_text='Threshold below which students are automatically flagged for retention (0-100).')),
                ('academic_year_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_configs_from', to='academics.academicyear')),
                ('academic_year_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_configs_to', to='academics.academicyear')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Config',
                'verbose_name_plural': 'Progression Configs',
                'ordering': ['-created_at'],
                'unique_together': {('academic_year_from', 'academic_year_to')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_average', models.FloatField(blank=True, help_text='Overall average (0-100) from Grade Entry.', null=True)),
                ('calculated_attendance_rate', models.FloatField(blank=True, help_text='Attendance rate percentage (0-100) for the academic year.', null=True)),
                ('calculation_basis', models.CharField(choices=[('complete', 'Complete — all assessments present'), ('zero_scored', 'Zero-scored — one or more absences recorded as zero'), ('redistributed', 'Redistributed — excused absence, remaining components scaled'), ('incomplete', 'Incomplete — missing grade data, cannot calculate')], default='incomplete', max_length=20)),
                ('system_suggested_outcome', models.CharField(blank=True, choices=[('promote', 'Promote'), ('retain', 'Retain'), ('promote_with_conditions', 'Promote with Conditions'), ('graduate', 'Graduate')], help_text='System-calculated suggestion based on averages and attendance.', max_length=30, null=True)),
                ('hod_recommendation', models.CharField(blank=True, choices=[('promote', 'Promote'), ('retain', 'Retain'), ('promote_with_conditions', 'Promote with Conditions'), ('graduate', 'Graduate')], help_text="HOD's recommended outcome for HOS review.", max_length=30, null=True)),
                ('hod_recommended_at', models.DateTimeField(blank=True, null=True)),
                ('hos_decision', models.CharField(blank=True, choices=[('promote', 'Promote'), ('retain', 'Retain'), ('promote_with_conditions', 'Promote with Conditions'), ('graduate', 'Graduate')], help_text='Final decision made by HOS.', max_length=30, null=True)),
                ('hos_decided_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, help_text='Required when HOD/HOS outcome differs from system suggestion.')),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('pending_hod_review', 'Pending HOD Review'), ('pending_hos_decision', 'Pending HOS Decision'), ('finalized', 'Finalized')], default='calculated', max_length=30)),
                ('hod_recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_recommendations', to=settings.AUTH_USER_MODEL)),
                ('hos_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hos_decisions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_cases', to='students.student')),
                ('progression_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='academics.progressionconfig')),
            ],
            options={
                'verbose_name': 'Progression Case',
                'verbose_name_plural': 'Progression Cases',
                'ordering': ['student'],
                'unique_together': {('student', 'progression_config')},
            },
        ),
    ]
