# Generated by Django 5.2.15 on 2026-07-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_progressionconfig_progressioncase'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressioncase',
            name='hos_return_comment',
            field=models.TextField(blank=True, help_text='Required when HOS returns a case to HOD for reconsideration.'),
        ),
        migrations.AddField(
            model_name='promotionrun',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotionrun',
            name='failed_detail_json',
            field=models.JSONField(blank=True, default=list, help_text='List of {student_id, reason} dicts for students that failed during execution.'),
        ),
    ]
