# Generated by Django 5.2.15 on 2026-07-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_progressioncase_hos_return_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionrun',
            name='processed_student_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of student PKs already processed (enables resume on interruption).'),
        ),
        migrations.AddField(
            model_name='promotionrun',
            name='status',
            field=models.CharField(default='pending', help_text='Run status: pending, in_progress, paused, interrupted, completed.', max_length=20),
        ),
    ]
