# Generated by Django 5.2.15 on 2026-07-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_remove_promotionrun_dead_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionrun',
            name='failed_student_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of student PKs that failed during execution (eligible for retry).'),
        ),
        migrations.AlterField(
            model_name='promotionrun',
            name='processed_student_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of student PKs successfully processed (enables resume on interruption).'),
        ),
    ]
