# Generated by Django 5.2.15 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0034_add_promotionrun_failed_student_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionconfig',
            name='recalc_completed_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of cases successfully recalculated in the last run.', null=True),
        ),
        migrations.AddField(
            model_name='progressionconfig',
            name='recalc_failed_details',
            field=models.JSONField(blank=True, default=list, help_text='List of {student_id, reason} dicts for students that failed during recalculation.'),
        ),
        migrations.AddField(
            model_name='progressionconfig',
            name='recalc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
