# Generated by Django 5.2.15 on 2026-07-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_add_abc_unique_constraints'),
        ('academics', '0036_add_academic_year_dates'),
    ]

    operations = [
    ]
