# Generated by Django 5.2.15 on 2026-07-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0036_add_academic_year_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='endterm_exam_end_date',
            field=models.DateField(blank=True, help_text='End of end-of-term examination period.', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='endterm_exam_start_date',
            field=models.DateField(blank=True, help_text='Start of end-of-term examination period.', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='midterm_exam_end_date',
            field=models.DateField(blank=True, help_text='End of mid-term examination period.', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='midterm_exam_start_date',
            field=models.DateField(blank=True, help_text='Start of mid-term examination period.', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='exam_end_date',
            field=models.DateField(blank=True, help_text='DEPRECATED — use endterm_exam_end_date.', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='exam_start_date',
            field=models.DateField(blank=True, help_text='DEPRECATED — use endterm_exam_start_date.', null=True),
        ),
    ]
