# Generated by Django 5.2.15 on 2026-07-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_merge_20260706_1234'),
        ('academics', '0038_backfill_endterm_exam_dates'),
    ]

    operations = [
    ]
