# Generated by Django 5.2.15 on 2026-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0038_backfill_endterm_exam_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published years are locked for Admin-level edits. Only Super Admin can unpublish.'),
        ),
    ]
