# Generated by Django 5.2.15 on 2026-07-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0039_add_is_published_to_academic_year'),
        ('academics', '0039_merge_20260707_0145'),
    ]

    operations = [
    ]
