# Generated by Django 5.2.16 on 2026-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_ecd_hod_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='previous_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original score before correction — retained for audit trail (FR-ACAD-008).', max_digits=5, null=True),
        ),
    ]
