# Generated by Django 5.2.16 on 2026-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0041_examscore_previous_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='endterm_grade_marking_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='Working days after end-term exam for teachers to enter grades (excludes weekends).'),
        ),
        migrations.AddField(
            model_name='term',
            name='midterm_grade_marking_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='Working days after mid-term exam for teachers to enter grades (excludes weekends).'),
        ),
        migrations.AddField(
            model_name='term',
            name='quiz_end_date',
            field=models.DateField(blank=True, help_text='End of quiz period for this term.', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='quiz_start_date',
            field=models.DateField(blank=True, help_text='Start of quiz period for this term.', null=True),
        ),
    ]
