# Generated by Django 5.2.15 on 2026-07-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_merge_20260714_2114'),
        ('academics', '0041_examscore_previous_score'),
    ]

    operations = [
    ]
