# Generated by Django 5.2.16 on 2026-08-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0042_add_quiz_dates_and_grade_marking_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='quiz_grade_marking_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='Working days after quiz period for teachers to enter grades (excludes weekends).'),
        ),
    ]
