# Generated by Django 5.2.15 on 2026-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0042_merge_20260726_1434'),
        ('academics', '0045_term_academic_year_protect'),
    ]

    operations = [
    ]
