# Generated by Django 5.2.16 on 2026-08-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0045_term_academic_year_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeclass',
            name='is_exit_grade',
            field=models.BooleanField(default=False, help_text='True for the highest grade (e.g. Grade 9)'),
        ),
    ]
