# Generated by Django 5.2.16 on 2026-08-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_gradeclass_is_exit_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECDDomainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.CharField(choices=[('pre_k', 'Pre-K'), ('kindergarten', 'Kindergarten'), ('pre_school', 'Pre-School'), ('abc', 'ABC Class')], max_length=20)),
                ('domain_name', models.CharField(max_length=100)),
                ('competencies', models.JSONField(default=list, help_text='List of competency strings for this domain')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['class_type', 'sort_order', 'domain_name'],
                'unique_together': {('class_type', 'domain_name')},
            },
        ),
    ]
