# Generated by Django 5.2.15 on 2026-08-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_merge_20260806_1334'),
        ('academics', '0048_seed_ecd_domains'),
    ]

    operations = [
    ]
