# Generated by Django 5.2.16 on 2026-08-07 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0048_seed_ecd_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_capacity', models.PositiveIntegerField(default=25)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_capacities', to='academics.academicyear')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_capacities', to='academics.gradeclass')),
            ],
            options={
                'verbose_name': 'Class Capacity',
                'verbose_name_plural': 'Class Capacities',
                'unique_together': {('grade_class', 'academic_year')},
            },
        ),
    ]
