# Generated by Django 5.2.16 on 2026-08-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0049_classcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_enrichment',
            field=models.BooleanField(default=False, help_text='Enrichment subjects (Bible, ICT, PE, etc.) use letter grades and one grade per term'),
        ),
    ]
