# Generated by Django 5.2.15 on 2026-08-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_merge_20260806_1334'),
        ('academics', '0051_subject_is_enrichment'),
    ]

    operations = [
    ]
