# Generated by Django 5.2.15 on 2026-08-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0052_merge_20260814_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'permissions': [('can_review_lessonplan', 'Can review and approve lesson plans')]},
        ),
    ]
