# Generated by Django 5.2.15 on 2026-08-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0053_alter_lessonplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressioncase',
            options={'ordering': ['student'], 'permissions': [('can_review_progression', 'Can review and recommend progression cases (department HODs)'), ('can_decide_progression', 'Can make final decisions on progression cases (HOS)')], 'verbose_name': 'Progression Case', 'verbose_name_plural': 'Progression Cases'},
        ),
    ]
