# Generated by Django 5.2.15 on 2026-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0054_alter_progressioncase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='day_of_week',
            field=models.CharField(blank=True, default='', help_text='Specific day (mon/tue/wed/thu/fri) for per-slot plans', max_length=8),
        ),
    ]
