# Generated by Django 5.2.15 on 2026-08-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0056_add_general_traits_to_reportcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'permissions': [('can_review_lessonplan', 'Can review and approve lesson plans'), ('view_all_lessonplans', 'Can view and create lesson plans for all teachers')]},
        ),
    ]
