# Generated by Django 5.2.15 on 2026-08-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_remove_lessonplan_idx_lp_teacher_and_more'),
        ('academics', '0049_merge_0046_merge_20260806_1334_0048_seed_ecd_domains'),
        ('academics', '0057_alter_lessonplan_options'),
    ]

    operations = [
    ]
