# Generated by Django 5.2.15 on 2026-09-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0058_ensure_change_examscore_perm'),
        ('academics', '0058_merge_20260829_1354'),
    ]

    operations = [
    ]
