# Generated by Django 5.2.17 on 2026-09-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0059_merge_20260902_1518'),
    ]

    # State-only: 0028 already drops these indexes with raw SQL (IF EXISTS), so
    # running RemoveIndex against the database again would fail on fresh DBs.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='lessonplan',
                    name='idx_lp_teacher',
                ),
                migrations.RemoveIndex(
                    model_name='lessonplan',
                    name='idx_lp_submitted_at',
                ),
                migrations.RemoveIndex(
                    model_name='reportcard',
                    name='idx_rc_student',
                ),
                migrations.RemoveIndex(
                    model_name='reportcard',
                    name='idx_rc_term',
                ),
                migrations.RemoveIndex(
                    model_name='reportcard',
                    name='idx_rc_is_ecd',
                ),
            ],
        ),
    ]
