# Generated by Django 5.2.18 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_reset_incomplete_pending_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='parent_signature_name',
            field=models.CharField(blank=True, help_text='Name of parent who signed', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='parent_signed',
            field=models.BooleanField(default=False, help_text='Whether parent has signed the report card'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='parent_signed_at',
            field=models.DateTimeField(blank=True, help_text='When parent signed', null=True),
        ),
    ]
