# Generated by Django 5.2.18 on 2026-10-07 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0062_student_parent_wording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScoreAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_amendments', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='academics.examscore')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
