# Generated by Django 5.2.18 on 2026-10-07 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0063_exam_score_amendment'),
        ('students', '0014_studentdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assessment_mode',
            field=models.CharField(choices=[('marks', 'Mark-bearing (Quiz, Mid Term, End Term)'), ('remark', 'Remark only (once per term, no marks)')], default='marks', help_text='Mark-bearing subjects take Quiz, Mid Term and End Term marks; remark-only subjects take one remark per term. Applies to Primary and Lower Secondary.', max_length=10),
        ),
        migrations.CreateModel(
            name='SubjectTermRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(db_index=True, max_length=80)),
                ('remark', models.CharField(choices=[('Outstanding', 'Outstanding'), ('High', 'High'), ('Good', 'Good'), ('Aspiring', 'Aspiring'), ('Basic', 'Basic'), ('Needs Improvement', 'Needs Improvement')], max_length=20)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_remarks_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_remarks', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_remarks', to='academics.term')),
            ],
            options={
                'unique_together': {('student', 'term', 'subject_name')},
            },
        ),
    ]
