# Generated by Django 5.2.18 on 2026-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0064_subject_assessment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='approver_entered',
            field=models.BooleanField(default=False, help_text='The approver also entered these marks (recorded at approval).'),
        ),
    ]
