# Generated by Django 5.2.13 on 2026-04-23 12:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='present', max_length=16)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('class_name', models.CharField(db_index=True, max_length=64)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrected', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'class_name'], name='attendance__date_19a526_idx'), models.Index(fields=['student', 'date'], name='attendance__student_3787a2_idx')],
                'unique_together': {('date', 'student')},
            },
        ),
    ]
