# Generated by Django 5.2.13 on 2026-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='is_early_departure',
            field=models.BooleanField(default=False),
        ),
    ]
