# Generated by Django 5.2.14 on 2026-05-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendanceentry_check_in_time_and_more'),
        ('hr', '0004_staffprofile_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='present', max_length=16)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='hr.staffprofile')),
            ],
            options={
                'verbose_name_plural': 'Staff Attendance Entries',
                'unique_together': {('date', 'staff')},
            },
        ),
    ]
