# Generated by Django 5.2.14 on 2026-05-21 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_staffattendanceentry'),
        ('students', '0006_laravelparent_studentlaravelparent_student_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Failed'), (3, 'Retry')], db_index=True, default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('laravel_message_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('notification_type', models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out'), ('otp', 'OTP Code'), ('absence', 'Absence Alert'), ('general', 'General')], max_length=20)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('laravel_parent_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='checkout_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='laravel_attendance_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['check_in_time'], name='attendance__check_i_8796ef_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['laravel_attendance_id'], name='attendance__laravel_ead43b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'created_at'], name='attendance__status_0a6960_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['phone', 'status'], name='attendance__phone_299dd2_idx'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='attendance_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='attendance.attendanceentry'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='students.parentguardian'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='otp_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='attendance.otpcode'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['parent', 'verified'], name='attendance__parent__1364e2_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['code', 'expires_at'], name='attendance__code_f53a19_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', 'delivery_status'], name='attendance__notific_14ff27_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient_phone', 'created_at'], name='attendance__recipie_43577d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['attendance_entry', 'notification_type'], name='attendance__attenda_50c843_idx'),
        ),
    ]
