# Generated by Django 5.2.15 on 2026-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_message_notificationlog_otpcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceentry',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='unconfirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='staffattendanceentry',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='present', max_length=16),
        ),
    ]
