# Generated by Django 5.2.15 on 2026-07-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staffattendanceentry',
            name='idx_sae_staff',
        ),
    ]
