# Generated by Django 5.2.16 on 2026-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_staffattendanceentry_idx_sae_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='original_status',
            field=models.CharField(blank=True, choices=[('unconfirmed', 'Unconfirmed'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], help_text='Original status before correction (preserved for audit trail).', max_length=16, null=True),
        ),
    ]
